data_dir = "/var/lib/vector"

##
## Sources
##

[sources.internal_metrics]
type = "internal_metrics"

[sources.syslog]
type = "syslog"
address = "0.0.0.0:8282"
max_length = 1_500_000
mode = "tcp"

##
## Transforms
##

[transforms.remap]
type = "remap"
inputs = ["syslog"]
source = ". |= parse_regex!(.host, r'^(?P<hostname>[a-z]+)\\.(?P<tld>[a-z]+)')"

[transforms.log2metric]
type = "log_to_metric"
inputs = ["remap"]

  [[transforms.log2metric.metrics]]
  type = "gauge"
  field = "procid"
  tags.hostname = "{{ hostname }}"
  tags.facility = "{{ facility }}"
  tags.severity = "{{ severity }}"

##
## Sinks
##

[sinks.prometheus]
type = "prometheus_exporter"
inputs = ["internal_metrics"]
address = "0.0.0.0:9090"

[sinks.datadog_metrics]
type = "datadog_metrics"
inputs = ["log2metric"]
endpoint = "http://localhost:8080"
default_api_key = "DEADBEEF"
default_namespace = "vector"
