[package]
name = "protobuf"
version = "0.1.0"
authors = ["Ana Hobden <operator@hoverbear.org>"]
edition = "2018"
build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
prost = "0.6"
serde_json = "1.0"
serde = "1.0"

[build-dependencies]
prost-build = "0.6"
