[sinks.aws_cloudwatch_logs]
title = "AWS Cloudwatch Logs"
beta = false
common = true
delivery_guarantee = "at_least_once"
egress_method = "batching"
function_category = "transmit"
healthcheck = true
input_types = ["log"]
requirements = {}
service_limits_short_link = "aws_cw_logs_service_limits"
service_providers = ["AWS"]
write_to_description = "[Amazon Web Service's CloudWatch Logs service][urls.aws_cw_logs] via the [`PutLogEvents` API endpoint](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html)"

<%= render("_partials/_aws_env_vars.toml", namespace: "sinks.aws_cloudwatch_logs.env_vars") %>

<%= render("_partials/_aws_options.toml", namespace: "sinks.aws_cloudwatch_logs.options") %>

<%= render("_partials/_component_options.toml", type: "sink", name: "aws_cloudwatch_logs") %>

<%= render("_partials/_batch_options.toml", namespace: "sinks.aws_cloudwatch_logs.options", common: false, max_events: nil, max_size: 1049000, timeout_secs: 1) %>

<%= render("_partials/_buffer_options.toml", namespace: "sinks.aws_cloudwatch_logs.options") %>

<%= render(
  "_partials/_request_options.toml",
  namespace: "sinks.aws_cloudwatch_logs.options",
  common: false,
  in_flight_limit: 5,
  rate_limit_duration_secs: 1,
  rate_limit_num: 5,
  retry_attempts: -1,
  retry_initial_backoff_secs: 1,
  retry_max_duration_secs: 10,
  timeout_secs: 30
) %>

[sinks.aws_cloudwatch_logs.options.encoding]
type = "string"
category = "requests"
common = true
required = true
description = """\
The encoding format used to serialize the events before outputting.\
"""

[sinks.aws_cloudwatch_logs.options.encoding.enum]
json = "Each event is encoded into JSON and the payload is represented as a JSON array."
text = "Each event is encoded into text via the `message` key and the payload is new line delimited."

[sinks.aws_cloudwatch_logs.options.group_name]
type = "string"
common = true
examples = [
  "{{ file }}",
  "ec2/{{ instance_id }}",
  "group-name"
]
required = true
partition_key = true
templateable = true
description = "The [group name][urls.aws_cw_logs_group_name] of the target CloudWatch Logs stream."

[sinks.aws_cloudwatch_logs.options.stream_name]
type = "string"
common = true
examples = [
  "{{ instance_id }}",
  "%Y-%m-%d",
  "stream-name"
]
required = true
partition_key = true
templateable = true
description = "The [stream name][urls.aws_cw_logs_stream_name] of the target CloudWatch Logs stream."

[sinks.aws_cloudwatch_logs.options.create_missing_group]
type = "bool"
common = true
default = true
description = """\
Dynamically create a [log group][urls.aws_cw_logs_group_name] if it does not already exist. This will ignore \
`create_missing_stream` directly after creating the group and will create the first stream.\
"""

[sinks.aws_cloudwatch_logs.options.create_missing_stream]
type = "bool"
common = true
default = true
description = "Dynamically create a [log stream][urls.aws_cw_logs_stream_name] if it does not already exist."

[[sinks.aws_cloudwatch_logs.output.examples]]
label = "Generic"
body = """\
```http
POST / HTTP/1.1
Host: logs.<region>.<domain>
X-Amz-Date: <date>
Accept: application/json
Content-Type: application/x-amz-json-1.1
Content-Length: <byte_size>
Connection: Keep-Alive
X-Amz-Target: Logs_20140328.PutLogEvents

{
  "logGroupName": "<group_name>",
  "logStreamName": "<stream_name>",
  "logEvents": [
    {
      "timestamp": <log_timestamp>,
      "message": "<json_encoded_log>"
    },
    {
      "timestamp": <log_timestamp>,
      "message": "<json_encoded_log>"
    },
    {
      "timestamp": <log_timestamp>,
      "message": "<json_encoded_log>"
    }
  ]
}
```\
"""
