[sinks.aws_cloudwatch_metrics]
title = "AWS Cloudwatch Metrics"
noun = "AWS Cloudwatch Metrics"
beta = true
common = false
delivery_guarantee = "at_least_once"
<%= render("_partials/descriptions/_aws_cloudwatch.toml") %>
egress_method = "streaming"
features = [
  "Send metrics to AWS Cloudwatch.",
  "Batch data to maximize throughput.",
  "Automatically retry failed requests, with backoff.",
  "Automatically aggregate metrics at the edge for improved performance.",
]
function_category = "transmit"
healthcheck = true
input_types = ["metric"]
requirements = {}
service_limits_short_link = "aws_cloudwatch_metrics_service_limits"
service_providers = ["AWS"]
write_to_description = "[Amazon Web Service's CloudWatch Metrics service][urls.aws_cloudwatch_metrics] via the [`PutMetricData` API endpoint](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_PutMetricData.html)"

<%= render("_partials/fields/_aws_env_vars.toml", namespace: "sinks.aws_cloudwatch_metrics.env_vars") %>

<%= render("_partials/fields/_aws_options.toml", namespace: "sinks.aws_cloudwatch_metrics.options") %>

<%= render("_partials/fields/_batch_options.toml", namespace: "sinks.aws_cloudwatch_metrics.options", common: false, max_events: 20, max_size: nil, timeout_secs: 1) %>

<%= render("_partials/fields/_component_options.toml", type: "sink", name: "aws_cloudwatch_metrics") %>

[sinks.aws_cloudwatch_metrics.options.namespace]
type = "string"
common = true
examples = ["service"]
required = true
description = "A [namespace](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_concepts.html#Namespace) that will isolate different metrics from each other."
