[sinks.aws_cloudwatch_logs]
batch_size = 1049000
batch_timeout = 1
beta = true
buffer = true
delivery_guarantee = "at_least_once"
egress_method = "batching"
healthcheck = true
input_types = ["log"]
rate_limit_duration = 1
rate_limit_num = 5
retry_attempts = 5
retry_backoff_secs = 1
request_in_flight_limit = 5
request_timeout_secs = 30
service_limits_short_link = "aws_cw_logs_service_limits"
service_provider = "AWS"
write_to_description = "[AWS CloudWatch Logs][urls.aws_cw_logs] via the [`PutLogEvents` API endpoint](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html)"

[sinks.aws_cloudwatch_logs.options.encoding]
type = "string"
category = "Requests"
enum = ["json", "text"]
null = true
description = """\
The encoding format used to serialize the events before flushing. The default \
is dynamic based on if the event is structured or not.\
"""

[sinks.aws_cloudwatch_logs.options.group_name]
type = "string"
examples = [
  "{{ file }}",
  "ec2/{{ instance_id }}",
  "group-name"
]
null = false
partition_key = true
templateable = true
description = "The [group name][urls.aws_cw_logs_group_name] of the target CloudWatch Logs stream."

[sinks.aws_cloudwatch_logs.options.region]
type = "string"
examples = ["us-east-1"]
null = false
description = "The [AWS region][urls.aws_cw_logs_regions] of the target CloudWatch Logs stream resides."

[sinks.aws_cloudwatch_logs.options.stream_name]
type = "string"
examples = [
  "{{ instance_id }}",
  "%Y-%m-%d",
  "stream-name"
]
null = false
partition_key = true
templateable = true
description = "The [stream name][urls.aws_cw_logs_stream_name] of the target CloudWatch Logs stream."

[sinks.aws_cloudwatch_logs.options.create_missing_group]
type = "bool"
default = true
null = true
description = """\
Dynamically create a [log group][urls.aws_cw_logs_group_name] if it does not already exist. This will ignore \
`create_missing_stream` directly after creating the group and will create the first stream. \
"""

[sinks.aws_cloudwatch_logs.options.create_missing_stream]
type = "bool"
default = true
null = true
description = "Dynamically create a [log stream][urls.aws_cw_logs_stream_name] if it does not already exist."
