[sinks.aws_kinesis_firehose]
title = "AWS Kinesis Firehose"
batch_max_events = 500
batch_timeout_secs = 1
beta = true
buffer = true
common = false
delivery_guarantee = "at_least_once"
egress_method = "batching"
encodings = ["json", "text"]
function_category = "transmit"
healthcheck = true
input_types = ["log"]
request_rate_limit_duration_secs = 1
request_rate_limit_num =5
request_retry_attempts = 5
request_retry_initial_backoff_secs = 1
request_retry_max_duration_secs = 10
request_in_flight_limit = 5
request_timeout_secs = 30
service_limits_short_link = "aws_kinesis_firehose_service_limits"
service_providers = ["AWS"]
write_to_description = "[Amazon Web Service's Kinesis Data Firehose][urls.aws_kinesis_data_firehose] via the [`PutRecordBatch` API endpoint](https://docs.aws.amazon.com/firehose/latest/APIReference/API_PutRecordBatch.html)"

[sinks.aws_kinesis_firehose.options.stream_name]
type = "string"
common = true
examples = ["my-stream"]
required = true
description = "The [stream name][urls.aws_cw_logs_stream_name] of the target Kinesis Firehose delivery stream."

[[sinks.aws_kinesis_firehose.output.examples]]
label = "Generic"
body = """\
```http
POST / HTTP/1.1
Host: firehose.<region>.<domain>
Content-Length: <byte_size>
Content-Type: application/x-amz-json-1.1
Connection: Keep-Alive
X-Amz-Target: Firehose_20150804.PutRecordBatch
{
    "DeliveryStreamName": "<stream_name>",
    "Records": [
        {
            "Data": "<base64_encoded_log>",
        },
        {
            "Data": "<base64_encoded_log>",
        },
        {
            "Data": "<base64_encoded_log>",
        },
    ]
}
```\
"""
