[sinks.aws_kinesis_firehose]
title = "AWS Kinesis Firehose"
beta = true
common = false
delivery_guarantee = "at_least_once"
egress_method = "batching"
function_category = "transmit"
healthcheck = true
input_types = ["log"]
requirements = {}
service_limits_short_link = "aws_kinesis_firehose_service_limits"
service_providers = ["AWS"]
write_to_description = "[Amazon Web Service's Kinesis Data Firehose][urls.aws_kinesis_data_firehose] via the [`PutRecordBatch` API endpoint](https://docs.aws.amazon.com/firehose/latest/APIReference/API_PutRecordBatch.html)"

<%= render("_partials/fields/_aws_env_vars.toml", namespace: "sinks.aws_kinesis_firehose.env_vars") %>

<%= render("_partials/fields/_aws_options.toml", namespace: "sinks.aws_kinesis_firehose.options") %>

<%= render("_partials/fields/_component_options.toml", type: "sink", name: "aws_kinesis_firehose") %>

<%= render("_partials/fields/_batch_options.toml", namespace: "sinks.aws_kinesis_firehose.options", common: false, max_events: 500, max_size: nil, timeout_secs: 1) %>

<%= render(
  "_partials/fields/_buffer_options.toml",
  namespace: "sinks.aws_kinesis_firehose.options",
  common: false
) %>

<%= render(
  "_partials/fields/_request_options.toml",
  namespace: "sinks.aws_kinesis_firehose.options",
  common: false,
  in_flight_limit: 5,
  rate_limit_duration_secs: 1,
  rate_limit_num: 5,
  retry_attempts: -1,
  retry_initial_backoff_secs: 1,
  retry_max_duration_secs: 10,
  timeout_secs: 30
) %>

<%= render("_partials/fields/_encoding_options.toml",
  namespace: "sinks.aws_kinesis_firehose.options",
  encodings: ["json", "text"]
) %>

[sinks.aws_kinesis_firehose.options.stream_name]
type = "string"
common = true
examples = ["my-stream"]
required = true
description = "The [stream name][urls.aws_cw_logs_stream_name] of the target Kinesis Firehose delivery stream."

[[sinks.aws_kinesis_firehose.output.examples]]
label = "Generic"
body = """\
```http
POST / HTTP/1.1
Host: firehose.<region>.<domain>
Content-Length: <byte_size>
Content-Type: application/x-amz-json-1.1
Connection: Keep-Alive
X-Amz-Target: Firehose_20150804.PutRecordBatch
{
    "DeliveryStreamName": "<stream_name>",
    "Records": [
        {
            "Data": "<base64_encoded_log>",
        },
        {
            "Data": "<base64_encoded_log>",
        },
        {
            "Data": "<base64_encoded_log>",
        },
    ]
}
```\
"""
