[sinks.aws_kinesis_streams]
title = "AWS Kinesis Data Streams"
beta = true
common = false
delivery_guarantee = "at_least_once"
egress_method = "batching"
function_category = "transmit"
healthcheck = true
input_types = ["log"]
requirements = {}
service_limits_short_link = "aws_kinesis_streams_service_limits"
service_providers = ["AWS"]
write_to_description = "[Amazon Web Service's Kinesis Data Stream service][urls.aws_kinesis_data_streams] via the [`PutRecords` API endpoint](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_PutRecords.html)"

<%= render("_partials/fields/_aws_env_vars.toml", namespace: "sinks.aws_kinesis_streams.env_vars") %>

<%= render("_partials/fields/_aws_options.toml", namespace: "sinks.aws_kinesis_streams.options") %>

<%= render("_partials/fields/_component_options.toml", type: "sinks", name: "aws_kinesis_streams") %>

<%= render("_partials/fields/_batch_options.toml", namespace: "sinks.aws_kinesis_streams.options", common: false, max_events: 500, max_size: nil, timeout_secs: 1) %>

<%= render(
  "_partials/fields/_buffer_options.toml",
  namespace: "sinks.aws_kinesis_streams.options",
  common: false
) %>

<%= render(
  "_partials/fields/_request_options.toml",
  namespace: "sinks.aws_kinesis_streams.options",
  common: false,
  in_flight_limit: 5,
  rate_limit_duration_secs: 1,
  rate_limit_num: 5,
  retry_attempts: -1,
  retry_initial_backoff_secs: 1,
  retry_max_duration_secs: 10,
  timeout_secs: 30
) %>

<%= render("_partials/fields/_encoding_options.toml",
  namespace: "sinks.aws_kinesis_streams.options",
  encodings: ["json", "text"]
) %>

[sinks.aws_kinesis_streams.options.partition_key_field]
type = "string"
common = true
examples = ["user_id"]
description = "The log field used as the Kinesis record's partition key value."

[sinks.aws_kinesis_streams.options.stream_name]
type = "string"
common = true
examples = ["my-stream"]
required = true
description = "The [stream name][urls.aws_cw_logs_stream_name] of the target Kinesis Logs stream."

[[sinks.aws_kinesis_streams.output.examples]]
label = "Generic"
body = """\
```http
POST / HTTP/1.1
Host: kinesis.<region>.<domain>
Content-Length: <byte_size>
Content-Type: application/x-amz-json-1.1
Connection: Keep-Alive
X-Amz-Target: Kinesis_20131202.PutRecords
{
    "Records": [
        {
            "Data": "<json_encoded_log>",
            "PartitionKey": "<partition_key>"
        },
        {
            "Data": "<json_encoded_log>",
            "PartitionKey": "<partition_key>"
        },
        {
            "Data": "<json_encoded_log>",
            "PartitionKey": "<partition_key>"
        },
    ],
    "StreamName": "<stream_name>"
}
```\
"""
