[sinks.aws_kinesis_streams]
batch_size = 1049000
batch_timeout = 1
beta = true
buffer = true
delivery_guarantee = "at_least_once"
egress_method = "batching"
healthcheck = true
input_types = ["log"]
rate_limit_duration = 1
rate_limit_num = 5
retry_attempts = 5
retry_backoff_secs = 1
request_in_flight_limit = 5
request_timeout_secs = 30
service_limits_short_link = "aws_kinesis_service_limits"
service_provider = "AWS"
write_to_description = "[AWS Kinesis Data Stream][url.aws_kinesis_data_streams] via the [`PutRecords` API endpoint](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_PutRecords.html)"

[sinks.aws_kinesis_streams.options.encoding]
type = "string"
category = "Requests"
enum = ["json", "text"]
null = true
description = """\
The encoding format used to serialize the events before flushing. The default \
is dynamic based on if the event is structured or not.\
"""

[sinks.aws_kinesis_streams.options.partition_key_field]
type = "string"
examples = ["user_id"]
null = true
description = "The log field used as the Kinesis record's partition key value."

[sinks.aws_kinesis_streams.options.region]
type = "string"
examples = ["us-east-1"]
null = false
description = "The [AWS region][url.aws_cw_logs_regions] of the target Kinesis stream resides."

[sinks.aws_kinesis_streams.options.stream_name]
type = "string"
examples = ["my-stream"]
null = false
description = "The [stream name][url.aws_cw_logs_stream_name] of the target Kinesis Logs stream."