[sinks.aws_kinesis_streams]
title = "AWS Kinesis Data Streams"
batch_max_events = 500
batch_timeout_secs = 1
beta = true
buffer = true
common = false
delivery_guarantee = "at_least_once"
egress_method = "batching"
encodings = ["json", "text"]
function_category = "transmit"
healthcheck = true
input_types = ["log"]
request_rate_limit_duration_secs = 1
request_rate_limit_num =5
request_retry_attempts = 5
request_retry_initial_backoff_secs = 1
request_retry_max_duration_secs = 10
request_in_flight_limit = 5
request_timeout_secs = 30
service_limits_short_link = "aws_kinesis_streams_service_limits"
service_providers = ["AWS"]
write_to_description = "[Amazon Web Service's Kinesis Data Stream service][urls.aws_kinesis_data_streams] via the [`PutRecords` API endpoint](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_PutRecords.html)"

[sinks.aws_kinesis_streams.options.partition_key_field]
type = "string"
common = true
examples = ["user_id"]
description = "The log field used as the Kinesis record's partition key value."

[sinks.aws_kinesis_streams.options.region]
type = "string"
common = true
examples = ["us-east-1"]
required = true
description = "The [AWS region][urls.aws_cw_logs_regions] of the target Kinesis stream resides."

[sinks.aws_kinesis_streams.options.stream_name]
type = "string"
common = true
examples = ["my-stream"]
required = true
description = "The [stream name][urls.aws_cw_logs_stream_name] of the target Kinesis Logs stream."

[[sinks.aws_kinesis_streams.output.examples]]
label = "Generic"
output.type = "http"
output.body = """\
POST / HTTP/1.1
Host: kinesis.<region>.<domain>
Content-Length: <byte_size>
Content-Type: application/x-amz-json-1.1
Connection: Keep-Alive
X-Amz-Target: Kinesis_20131202.PutRecords
{
    "Records": [
        {
            "Data": "<json_encoded_log>",
            "PartitionKey": "<partition_key>"
        },
        {
            "Data": "<json_encoded_log>",
            "PartitionKey": "<partition_key>"
        },
        {
            "Data": "<json_encoded_log>",
            "PartitionKey": "<partition_key>"
        },
    ],
    "StreamName": "<stream_name>"
}\
"""
