[sinks.blackhole]
title = "Blackhole"
beta = false
common = false
delivery_guarantee = "best_effort"
egress_method = "streaming"
function_category = "test"
healthcheck = true
input_types = ["log", "metric"]
requirements = {}
write_to_description = """\
a blackhole that simply discards data, designed for testing and \
benchmarking purposes\
"""

<%= render(
  "_partials/fields/_component_options.toml",
  type: "sink",
  name: "blackhole",
  healthcheck: false
) %>

[sinks.blackhole.options.print_amount]
type = "int"
common = true
examples = [1000]
required = true
description = "The number of events that must be received in order to print a summary of activity."
