[sinks.blackhole]
title = "Blockhole"
buffer = false
common = false
delivery_guarantee = "best_effort"
egress_method = "streaming"
function_category = "test"
healthcheck = true
input_types = ["log", "metric"]
write_to_description = """\
a blackhole that simply discards data, designed for testing and \
benchmarking purposes\
"""

[sinks.blackhole.options.print_amount]
type = "int"
common = true
examples = [1000]
required = true
description = "The number of events that must be received in order to print a summary of activity."
