[sinks.clickhouse]
batch_size = 1049000
batch_timeout = 1
beta = true
buffer = false
delivery_guarantee = "best_effort"
healthcheck = true
egress_method = "batching"
input_types = ["log"]
rate_limit_duration = 1
rate_limit_num = 5
retry_attempts = 9223372036854775807
retry_backoff_secs = 1
request_in_flight_limit = 5
request_timeout_secs = 30
write_to_description = "[Clickhouse][urls.clickhouse] via the [`HTTP` Interface][urls.clickhouse_http]"

[sinks.clickhouse.options.compression]
type = "string"
category = "Requests"
enum = ["gzip"]
null = true
simple = true
description = "The compression type to use before writing data."

[sinks.clickhouse.options.host]
type = "string"
examples = ["http://localhost:8123"]
null = false
description = "The host url of the [Clickhouse][urls.clickhouse] server."

[sinks.clickhouse.options.table]
type = "string"
examples = ["mytable"]
null = false
description = "The table that data will be inserted into."

[sinks.clickhouse.options.database]
type = "string"
examples = ["mydatabase"]
null = true
description = "The database that contains the stable that data will be inserted into."

[sinks.clickhouse.options.basic_auth]
type = "table"
null = true
description = "Options for basic authentication."

[sinks.clickhouse.options.basic_auth.options.password]
type = "string"
examples = ["password"]
null = false
description = "The basic authentication password."

[sinks.clickhouse.options.basic_auth.options.user]
type = "string"
examples = ["username"]
null = false
description = "The basic authentication user name."
