[sinks.clickhouse]
title = "Clickhouse"
beta = true
common = true
delivery_guarantee = "best_effort"
function_category = "transmit"
healthcheck = true
egress_method = "batching"
input_types = ["log"]
requirements.clickhouse = ">= 1.1.54378"
write_to_description = "[Clickhouse][urls.clickhouse] via the [`HTTP` Interface][urls.clickhouse_http]"

<%= render("_partials/fields/_component_options.toml", type: "sink", name: "clickhouse") %>

<%= render("_partials/fields/_batch_options.toml", namespace: "sinks.clickhouse.options", common: false, max_events: nil, max_size: 1049000, timeout_secs: 1) %>

<%= render(
  "_partials/fields/_buffer_options.toml",
  namespace: "sinks.clickhouse.options",
  common: false
) %>

<%= render(
  "_partials/fields/_request_options.toml",
  namespace: "sinks.clickhouse.options",
  common: false,
  in_flight_limit: 5,
  rate_limit_duration_secs: 1,
  rate_limit_num: 5,
  retry_attempts: -1,
  retry_initial_backoff_secs: 1,
  retry_max_duration_secs: 10,
  timeout_secs: 30
) %>

[sinks.clickhouse.options.auth]
type = "table"
common = false
description = "Options for the authentication strategy."

[sinks.clickhouse.options.auth.children.strategy]
type = "string"
required = true
sort = 1
description = "The authentication strategy to use."

[sinks.clickhouse.options.auth.children.strategy.enum]
basic = "The [basic authentication strategy][urls.basic_auth]."

[sinks.clickhouse.options.auth.children.password]
type = "string"
examples = ["${PASSWORD_ENV_VAR}", "password"]
relevant_when = {strategy = "basic"}
required = true
description = "The basic authentication password."

[sinks.clickhouse.options.auth.children.user]
type = "string"
examples = ["${USERNAME_ENV_VAR}", "username"]
relevant_when = {strategy = "basic"}
required = true
description = "The basic authentication user name."

[sinks.clickhouse.options.compression]
type = "string"
category = "requests"
common = true
default = "none"
description = """\
The compression strategy used to compress the encoded event data before \
outputting.\
"""

[sinks.clickhouse.options.compression.enum]
none = "The payload will not be compressed."
gzip = "The payload will be compressed in [Gzip][urls.gzip] format before being sent."

[sinks.clickhouse.options.host]
type = "string"
common = true
examples = ["http://localhost:8123"]
required = true
description = "The host url of the [Clickhouse][urls.clickhouse] server."

[sinks.clickhouse.options.table]
type = "string"
common = true
examples = ["mytable"]
required = true
description = "The table that data will be inserted into."

<%= render("_partials/fields/_tls_connector_options.toml", namespace: "sinks.clickhouse.options", can_enable: false, can_verify_certificate: true, can_verify_hostname: false) %>

[sinks.clickhouse.options.database]
type = "string"
common = true
examples = ["mydatabase"]
description = "The database that contains the stable that data will be inserted into."

<%= render("_partials/fields/_encoding_options.toml",
  namespace: "sinks.clickhouse.options",
  encodings: [],
  common: ["timestamp_format"]
) %>
