[sinks.clickhouse]
title = "Clickhouse"
batch_max_size = 1049000
batch_timeout_secs = 1
beta = true
buffer = true
common = true
compressions  = ["gzip"]
delivery_guarantee = "best_effort"
function_category = "transmit"
healthcheck = true
egress_method = "batching"
input_types = ["log"]
request_rate_limit_duration_secs = 1
request_rate_limit_num =5
request_retry_attempts = 9223372036854775807
request_retry_backoff_secs = 1
request_in_flight_limit = 5
request_timeout_secs = 30
write_to_description = "[Clickhouse][urls.clickhouse] via the [`HTTP` Interface][urls.clickhouse_http]"
tls_options = []

[sinks.clickhouse.options.auth]
type = "table"
common = false
description = "Options for the authentication strategy."

[sinks.clickhouse.options.auth.options.strategy]
type = "string"
required = true
description = "The authentication strategy to use."

[sinks.clickhouse.options.auth.options.strategy.enum]
basic = "The [basic authentication strategy][urls.basic_auth]."

[sinks.clickhouse.options.auth.options.password]
type = "string"
examples = ["${PASSWORD_ENV_VAR}", "password"]
required = true
relevant_when = {strategy = "basic"}
description = "The basic authentication password."

[sinks.clickhouse.options.auth.options.user]
type = "string"
examples = ["${USERNAME_ENV_VAR}", "username"]
required = true
relevant_when = {strategy = "basic"}
description = "The basic authentication user name."

[sinks.clickhouse.options.host]
type = "string"
common = true
examples = ["http://localhost:8123"]
required = true
description = "The host url of the [Clickhouse][urls.clickhouse] server."

[sinks.clickhouse.options.table]
type = "string"
common = true
examples = ["mytable"]
required = true
description = "The table that data will be inserted into."

[sinks.clickhouse.options.database]
type = "string"
common = true
examples = ["mydatabase"]
description = "The database that contains the stable that data will be inserted into."
