[sinks.console]
title = "Console"
buffer = false
common = false
delivery_guarantee = "best_effort"
egress_method = "streaming"
encodings = ["json", "text"]
function_category = "test"
healthcheck = true
input_types = ["log", "metric"]
write_to_description = "[standard output streams][urls.standard_streams], such as `STDOUT` and `STDERR`"

[sinks.console.options.target]
type = "string"
common = true
default = "stdout"
required = true
description = "The [standard stream][urls.standard_streams] to write to."

[sinks.console.options.target.enum]
stdout = "Output will be written to [STDOUT][urls.stdout]"
stderr = "Output will be written to [STDERR][urls.stderr]"
