[sinks.console]
title = "Console"
beta = false
common = false
delivery_guarantee = "best_effort"
egress_method = "streaming"
function_category = "test"
healthcheck = true
input_types = ["log", "metric"]
requirements = {}
write_to_description = "[standard output streams][urls.standard_streams], such as `STDOUT` and `STDERR`"

<%= render(
  "_partials/fields/_component_options.toml",
  type: "sink",
  name: "console",
  healthcheck: false
) %>

<%= render(
  "_partials/fields/_encoding_options.toml",
  namespace: "sinks.console.options",
  encodings: ["json", "text"]
) %>

[sinks.console.options.target]
type = "string"
common = true
default = "stdout"
description = "The [standard stream][urls.standard_streams] to write to."

[sinks.console.options.target.enum]
stdout = "Output will be written to [STDOUT][urls.stdout]"
stderr = "Output will be written to [STDERR][urls.stderr]"
