[sinks.console]
title = "Console"
beta = false
common = false
delivery_guarantee = "best_effort"
egress_method = "streaming"
function_category = "test"
healthcheck = true
input_types = ["log", "metric"]
write_to_description = "[standard output streams][urls.standard_streams], such as `STDOUT` and `STDERR`"

<%= render("_partials/_component_options.toml", type: "sink", name: "console") %>

[sinks.console.options.encoding]
type = "string"
category = "requests"
common = true
required = true
description = """\
The encoding format used to serialize the events before outputting.\
"""

[sinks.console.options.encoding.enum]
json = "Each event is encoded into JSON."
text = "Each event is encoded into text via the `message` key."

[sinks.console.options.target]
type = "string"
common = true
default = "stdout"
required = true
description = "The [standard stream][urls.standard_streams] to write to."

[sinks.console.options.target.enum]
stdout = "Output will be written to [STDOUT][urls.stdout]"
stderr = "Output will be written to [STDERR][urls.stderr]"
