[sinks.datadog_logs]
title = "Datadog Logs"
beta = true
common = false
delivery_guarantee = "best_effort"
egress_method = "streaming"
function_category = "transmit"
healthcheck = true
input_types = ["log"]
service_providers = ["Datadog"]
write_to_description = "[Datadog's][urls.datadog] logs via the [TCP endpoint][urls.datadog_logs_endpoints]"
requirements = {}

<%= render("_partials/_component_options.toml", type: "sink", name: "datadog_logs") %>

<%= render("_partials/_buffer_options.toml", namespace: "sinks.datadog_logs.options") %>

<%= render("_partials/_encoding.toml",
  namespace: "sinks.datadog_logs.options",
  encodings: ["json", "text"]
) %>

[sinks.datadog_logs.options.api_key]
type = "string"
common = true
examples = ["${DATADOG_API_KEY_ENV_VAR}", "ef8d5de700e7989468166c40fc8a0ccd"]
required = true
description = "Datadog [API key](https://docs.datadoghq.com/api/?lang=bash#authentication)"

[sinks.datadog_logs.options.endpoint]
type = "string"
required = false
default = "intake.logs.datadoghq.com:10516"
examples = ["127.0.0.1:8080", "example.com:12345"]
description = "The endpoint to stream logs to."

<%= render("_partials/_tls_connector_options.toml", namespace: "sinks.datadog_logs.options", can_enable: true, can_verify_certificate: true, can_verify_hostname: true) %>
