[sinks.file]
title = "File"
beta = false
common = false
delivery_guarantee = "best_effort"
egress_method = "streaming"
function_category = "transmit"
healthcheck = false
input_types = ["log"]
write_to_description = "a file"

<%= render("_partials/_component_options.toml", type: "sink", name: "file") %>

[sinks.file.options.encoding]
type = "string"
category = "requests"
common = true
required = true
description = """\
The encoding format used to serialize the events before outputting.\
"""

[sinks.file.options.encoding.enum]
ndjson = "Each event is encoded into JSON and the payload is new line delimited."
text = "Each event is encoded into text via the `message` key and the payload is new line delimited."

[sinks.file.options.path]
type = "string"
common = true
examples = [
  "vector-%Y-%m-%d.log",
  "application-{{ application_id }}-%Y-%m-%d.log"
]
required = true
templateable = true
description = "File name to write events to."

[sinks.file.options.idle_timeout_secs]
type = "int"
default = "30"
description = """\
The amount of time a file can be idle  and stay open. \
After not receiving any events for this timeout, the file will be flushed and \
closed.
"""
