[sinks.gcp_pubsub]
title = "GCP PubSub"
beta = true
common = true
delivery_guarantee = "best_effort"
function_category = "transmit"
healthcheck = true
egress_method = "batching"
input_types = ["log"]
requirements = {}
service_providers = ["Google"]
write_to_description = "[Google Cloud Platform's Pubsub service][urls.gcp_pubsub] via the [REST Interface][urls.gcp_pubsub_rest]"

<%= render("_partials/fields/_component_options.toml", type: "sink", name: "gcp_pubsub") %>

<%= render("_partials/fields/_batch_options.toml", namespace: "sinks.gcp_pubsub.options", common: false, max_events: nil, max_size: 10485760, timeout_secs: 1) %>

<%= render(
  "_partials/fields/_buffer_options.toml",
  namespace: "sinks.gcp_pubsub.options",
  common: false
) %>

<%= render(
  "_partials/fields/_request_options.toml",
  namespace: "sinks.gcp_pubsub.options",
  common: false,
  in_flight_limit: 5,
  rate_limit_duration_secs: 1,
  rate_limit_num: 100,
  retry_attempts: -1,
  retry_initial_backoff_secs: 1,
  retry_max_duration_secs: 10,
  timeout_secs: 60
) %>

<%= render("_partials/fields/_gcp.toml", namespace: "sinks.gcp_pubsub", access: "pubsub project and topic", required: false) %>

[sinks.gcp_pubsub.options.api_key]
type = "string"
examples = ["${GCP_API_KEY_ENV_VAR}", "ef8d5de700e7989468166c40fc8a0ccd"]
description = """\
A [Google Cloud API key][urls.gcp_authentication_api_key] used to authenticate access the pubsub project and topic. \
Either this or `credentials_path` must be set.\
"""

[sinks.gcp_pubsub.options.project]
type = "string"
common = false
required = true
examples = ["vector-123456"]
description = "The project name to which to publish logs."

<%= render("_partials/fields/_tls_connector_options.toml", namespace: "sinks.gcp_pubsub.options", can_enable: false, can_verify_certificate: true, can_verify_hostname: true) %>

[sinks.gcp_pubsub.options.topic]
type = "string"
common = false
required = true
examples = ["this-is-a-topic"]
description = "The topic within the project to which to publish logs."

<%= render("_partials/fields/_encoding_options.toml",
  namespace: "sinks.gcp_pubsub.options",
  encodings: []
) %>
