[sinks.gcp_pubsub]
batch_size = 10485760
batch_timeout = 1
beta = true
buffer = true
common = true
#compressions  = ["gzip"]
delivery_guarantee = "best_effort"
function_category = "transmit"
healthcheck = true
egress_method = "batching"
input_types = ["log"]
request_rate_limit_duration_secs = 1
request_rate_limit_num = 100
request_retry_attempts = 9223372036854775807
request_retry_backoff_secs = 1
request_in_flight_limit = 5
request_timeout_secs = 60
write_to_description = "[Pubsub][urls.gcp_pubsub] via the [REST Interface][urls.gcp_pubsub_rest]"
tls_options = []

[sinks.gcp_pubsub.options.api_key]
type = "string"
null = true
description = """\
A Google Cloud API key used to authenticate access the pubsub project and topic. \
Either this or `credentials_path` must be set.\
"""

[sinks.gcp_pubsub.options.credentials_path]
type = "string"
null = true
description = """\
The filename for a Google Cloud service account credentials JSON file \
used to authenticate access to the pubsub project and topic. \
Either this or `api_key` must be set.\
"""

[sinks.gcp_pubsub.options.project]
type = "string"
common = false
null = false
examples = ["vector-123456"]
description = "The project name to which to publish logs."

[sinks.gcp_pubsub.options.topic]
type = "string"
common = false
null = false
examples = ["this-is-a-topic"]
description = "The topic within the project to which to publish logs."
