[sinks.gcp_stackdriver_logging]
title = "GCP Stackdriver Logging"
beta = true
common = true
delivery_guarantee = "best_effort"
function_category = "transmit"
healthcheck = true
egress_method = "batching"
input_types = ["log"]
requirements = {}
service_providers = ["Google"]
write_to_description = "[Google Cloud Platform's Stackdriver Logging service][urls.gcp_stackdriver_logging] via the [REST Interface][urls.gcp_stackdriver_logging_rest]"

<%= render("_partials/fields/_component_options.toml", type: "sink", name: "gcp_stackdriver_logging") %>

<%= render("_partials/fields/_batch_options.toml", namespace: "sinks.gcp_stackdriver_logging.options", common: false, max_events: nil, max_size: 5242880, timeout_secs: 1) %>

<%= render(
  "_partials/fields/_buffer_options.toml",
  namespace: "sinks.gcp_stackdriver_logging.options",
  common: false
) %>

<%= render(
  "_partials/fields/_request_options.toml",
  namespace: "sinks.gcp_stackdriver_logging.options",
  common: false,
  in_flight_limit: 5,
  rate_limit_duration_secs: 1,
  rate_limit_num: 1000,
  retry_attempts: -1,
  retry_initial_backoff_secs: 1,
  retry_max_duration_secs: 10,
  timeout_secs: 60
) %>

<%= render("_partials/fields/_gcp.toml", namespace: "sinks.gcp_stackdriver_logging", access: "Stackdriver Logging API", required: true) %>

[sinks.gcp_stackdriver_logging.options.project_id]
type = "string"
common = false
required = true
examples = ["vector-123456"]
description = """\
The project ID to which to publish logs. See the \
[Google Cloud Platform project management documentation][urls.gcp_projects] \
for more details.

Exactly one of `billing_account_id`, `folder_id`, `organization_id`, or \
`project_id` must be set.\
"""

[sinks.gcp_stackdriver_logging.options.billing_account_id]
type = "string"
common = false
examples = ["012345-6789AB-CDEF01"]
description = """\
The billing account ID to which to publish logs.

Exactly one of `billing_account_id`, `folder_id`, `organization_id`, or \
`project_id` must be set.\
"""

[sinks.gcp_stackdriver_logging.options.folder_id]
type = "string"
common = false
examples = ["My Folder"]
description = """\
The folder ID to which to publish logs.
See the [Google Cloud Platform folder documentation][urls.gcp_folders] for \
more details.

Exactly one of `billing_account_id`, `folder_id`, `organization_id`, or \
`project_id` must be set.\
"""

[sinks.gcp_stackdriver_logging.options.log_id]
type = "string"
common = false
required = true
examples = ["vector-logs"]
description = """\
The log ID to which to publish logs. This is a name you create to identify \
this log stream.\
"""

[sinks.gcp_stackdriver_logging.options.organization_id]
type = "string"
common = false
examples = ["622418129737"]
description = """\
The organization ID to which to publish logs. This would be the identifier \
assigned to your organization on Google Cloud Platform.

Exactly one of `billing_account_id`, `folder_id`, `organization_id`, or \
`project_id` must be set.\
"""

[sinks.gcp_stackdriver_logging.options.resource]
type = "table"
description = "Options for describing the logging resource."

[sinks.gcp_stackdriver_logging.options.resource.children.type]
type = "string"
required = true
examples = ["global", "gce_instance"]
description = """\
The monitored resource type. For example, the type of a Compute Engine VM \
instance is gce_instance.

See the [Google Cloud Platform monitored resource documentation][urls.gcp_resources] \
for more details.\
"""

[sinks.gcp_stackdriver_logging.options.resource.children."`[label]`"]
type = "string"
examples = [
  {projectId = "vector-123456"},
  {zone = "Twilight"},
]
description = """\
Values for all of the labels listed in the associated monitored resource descriptor.

For example, Compute Engine VM instances use the labels `projectId`, \
`instanceId`, and `zone`.\
"""

<%= render("_partials/fields/_tls_connector_options.toml", namespace: "sinks.gcp_stackdriver_logging.options", can_enable: false, can_verify_certificate: true, can_verify_hostname: false) %>

<%= render("_partials/fields/_encoding_options.toml",
  namespace: "sinks.gcp_stackdriver_logging.options",
  encodings: []
) %>
