[sinks.http]
batch_is_simple = true
batch_size = 1049000
batch_timeout = 1
buffer = true
common = true
compressions = ["gzip"]
delivery_guarantee = "at_least_once"
egress_method = "batching"
encodings = ["ndjson", "json", "text"]
function_category = "transmit"
healthcheck = true
input_types = ["log"]
request_rate_limit_duration_secs = 1
request_rate_limit_num = 10
request_retry_attempts = 10
request_retry_backoff_secs = 1
request_in_flight_limit = 10
request_timeout_secs = 30
write_to_description = "a generic HTTP endpoint"
tls_options = []

[sinks.http.options.basic_auth]
type = "table"
common = true
null = true
description = "Options for basic authentication."

[sinks.http.options.basic_auth.options.password]
type = "string"
examples = ["${PASSWORD_ENV_VAR}", "password"]
null = false
description = "The basic authentication password."

[sinks.http.options.basic_auth.options.user]
type = "string"
examples = ["${USERNAME_ENV_VAR}", "username"]
null = false
description = "The basic authentication user name."

[sinks.http.options.headers]
type = "table"
null = true
description = "Options for custom headers."

[sinks.http.options.headers.options."`[header-key]`"]
type = "string"
examples = [
  {"Authorization" = "${TOKEN_ENV_VAR}"},
  {"X-Powered-By" = "Vector"},
]
null = false
description = "A custom header to be added to each outgoing HTTP request."

[sinks.http.options.healthcheck_uri]
type = "string"
examples = ["https://10.22.212.22:9000/_health"]
null = true
description = "A URI that Vector can request in order to determine the service health."

[sinks.http.options.uri]
type = "string"
common = true
examples = ["https://10.22.212.22:9000/endpoint"]
null = false
description = "The full URI to make HTTP requests to. This should include the protocol and host, but can also include the port, path, and any other valid part of a URI."

[[sinks.http.output.examples]]
label = "JSON"
body = """\
```http
POST <uri> HTTP/1.1
Host: <uri.host>
Content-Type: application/x-ndjson
Content-Length: <byte_size>

[
  <json_encoded_log>,
  <json_encoded_log>,
  <json_encoded_log>,
]
```\
"""

[[sinks.http.output.examples]]
label = "NDJSON"
body = """\
```http
POST <uri> HTTP/1.1
Host: <uri.host>
Content-Type: application/x-ndjson
Content-Length: <byte_size>

<json_encoded_log>
<json_encoded_log>
<json_encoded_log>
```\
"""

[[sinks.http.output.examples]]
label = "Text"
body = """\
```http
POST <uri> HTTP/1.1
Host: <uri.host>
Content-Type: text/plain
Content-Length: <byte_size>

<log.message>
<log.message>
<log.message>
```\
"""
