[sinks.humio]
title = "Humio"
batch_max_size = 1049000
batch_timeout_secs = 1
buffer = true
common = false
beta = true
delivery_guarantee = "at_least_once"
egress_method = "batching"
function_category = "transmit"
healthcheck = true
input_types = ["log"]
request_rate_limit_duration_secs = 1
request_rate_limit_num =10
request_retry_attempts = 5
request_retry_initial_backoff_secs = 1
request_retry_max_duration_secs = 10
request_in_flight_limit = 10
request_timeout_secs = 60
write_to_description = "[Humio][urls.humio] via the [HEC API][urls.humio_hec]"

[sinks.humio.options.token]
type = "string"
common = true
examples = ["${TOKEN_ENV_VAR}", "A94A8FE5CCB19BA61C4C08"]
required = true
description = "Your Humio ingestion token."

[sinks.humio.options.host]
type = "string"
examples = ["http://myhumiohost.com"]
required = false
description = "The optional host to send Humio logs to."

[sinks.humio.options.encoding]
type = "string"
examples = ["text", "json"]
default = "json"
required = false
description = """
The encoding type that will be used to send logs. \
If `text` is selected Vector will attempt to use the `message` \
field to send as the main event payload. If `json` is selected \
the entire event will be encoded as a json object and set as the \
event field.

For more information on how these specific details are handled within \
Humio check out the [Humio HEC][urls.humio_hec] docs.\
"""
