[sinks.humio_logs]
title = "Humio Logs"
common = false
beta = true
delivery_guarantee = "at_least_once"
egress_method = "batching"
function_category = "transmit"
healthcheck = true
input_types = ["log"]
requirements = {}
write_to_description = "[Humio][urls.humio] via the [HEC API][urls.humio_hec]"

<%= render("_partials/fields/_component_options.toml", type: "sink", name: "humio_logs") %>

<%= render("_partials/fields/_batch_options.toml", namespace: "sinks.humio_logs.options", common: false, max_events: nil, max_size: 1049000, timeout_secs: 1) %>

<%= render(
  "_partials/fields/_buffer_options.toml",
  namespace: "sinks.humio_logs.options",
  common: false
) %>

<%= render(
  "_partials/fields/_request_options.toml",
  namespace: "sinks.humio_logs.options",
  common: false,
  in_flight_limit: 10,
  rate_limit_duration_secs: 1,
  rate_limit_num: 10,
  retry_attempts: -1,
  retry_initial_backoff_secs: 1,
  retry_max_duration_secs: 10,
  timeout_secs: 60
) %>

[sinks.humio_logs.options.token]
type = "string"
common = true
examples = ["${TOKEN_ENV_VAR}", "A94A8FE5CCB19BA61C4C08"]
required = true
description = "Your Humio ingestion token."

[sinks.humio_logs.options.host]
type = "string"
examples = ["http://myhumiohost.com"]
required = false
description = "The optional host to send Humio logs to."

<%= render("_partials/fields/_encoding_options.toml",
  namespace: "sinks.humio_logs.options",
  encodings: ["json"],
  default: "json"
) %>
