[sinks.kafka]
buffer = true
common = true
delivery_guarantee = "at_least_once"
egress_method = "streaming"
encodings = ["json", "text"]
function_category = "transmit"
healthcheck = true
input_types = ["log"]
service_provider = "Confluent"
write_to_description = "[Apache Kafka][urls.kafka] via the [Kafka protocol][urls.kafka_protocol]"
tls_options = ["+enabled", "-verify"]

[sinks.kafka.options.bootstrap_servers]
type = "[string]"
common = true
examples = [["10.14.22.123:9092", "10.14.23.332:9092"]]
null = false
description = """\
A list of host and port pairs that the Kafka client should contact to bootstrap \
its cluster metadata.\
"""

[sinks.kafka.options.key_field]
type = "string"
common = true
examples = ["user_id"]
null = false
description = """\
The log field name to use for the topic key. If unspecified, the key will be \
randomly generated. If the field does not exist on the log, a blank value \
will be used.\
"""

[sinks.kafka.options.topic]
type = "string"
common = true
examples = ["topic-1234"]
null = false
description = "The Kafka topic name to write events to."
