[sinks.kafka]
title = "Kafka"
beta = false
common = true
delivery_guarantee = "at_least_once"
egress_method = "streaming"
function_category = "transmit"
healthcheck = true
input_types = ["log"]
min_version = "0.8"
requirements = {}
service_providers = ["AWS", "Confluent"]
write_to_description = "[Apache Kafka][urls.kafka] via the [Kafka protocol][urls.kafka_protocol]"

<%= render("_partials/_component_options.toml", type: "sink", name: "kafka") %>

<%= render("_partials/_buffer_options.toml", namespace: "sinks.kafka.options") %>

[sinks.kafka.options.bootstrap_servers]
type = "string"
common = true
examples = ["10.14.22.123:9092,10.14.23.332:9092"]
required = true
description = """\
A comma delimited list of host and port pairs that the Kafka client should contact to bootstrap \
its cluster metadata.\
"""

<%= render("_partials/_encoding.toml",
  namespace: "sinks.kafka.options",
  encodings: ["json", "text"],
  default: false
) %>

[sinks.kafka.options.key_field]
type = "string"
common = true
examples = ["user_id"]
required = true
description = """\
The log field name to use for the topic key. If unspecified, the key will be \
randomly generated. If the field does not exist on the log, a blank value \
will be used.\
"""

<%= render("_partials/_tls_connector_options.toml", namespace: "sinks.kafka.options", can_enable: true, can_verify: false) %>

[sinks.kafka.options.topic]
type = "string"
common = true
examples = ["topic-1234"]
required = true
description = "The Kafka topic name to write events to."

[sinks.kafka.options.socket_timeout_ms]
type = "int"
examples = [30000, 90000]
default = 60000
description = "Default timeout for network requests."

[sinks.kafka.options.message_timeout_ms]
type = "int"
examples = [150000, 450000]
default = 300000
description = "Local message timeout."

[sinks.kafka.options.librdkafka_options]
type = "table"
category = "Advanced"
description = """\
Advanced producer options. See [`librdkafka` documentation][urls.lib_rdkafka_config] for details.
"""

[sinks.kafka.options.librdkafka_options.children."`[field-name]`"]
type = "string"
examples = [
  {"client.id" = "${ENV_VAR}"},
  {"socket.send.buffer.bytes" = "100"},
]
description = """\
The options and their values. Accepts `string` values.
"""
