[sinks.new_relic_logs]
title = "New Relic Logs"
beta = true
common = false
delivery_guarantee = "at_least_once"
egress_method = "batching"
function_category = "transmit"
input_types = ["log"]
healthcheck = true
requirements = {}
service_providers = ["New Relic"]
write_to_description = "[New Relic's log service][urls.new_relic] via their [log API][urls.new_relic_log_api]"

<%= render("_partials/fields/_component_options.toml", type: "sink", name: "new_relic_logs") %>

<%= render("_partials/fields/_batch_options.toml", namespace: "sinks.new_relic_logs.options", common: false, max_events: nil, max_size: 524000, timeout_secs: 1) %>

<%= render(
  "_partials/fields/_buffer_options.toml",
  namespace: "sinks.new_relic_logs.options",
  common: false
) %>

<%= render(
  "_partials/fields/_request_options.toml",
  namespace: "sinks.new_relic_logs.options",
  common: false,
  in_flight_limit: 5,
  rate_limit_duration_secs: 1,
  rate_limit_num: 100,
  retry_attempts: -1,
  retry_initial_backoff_secs: 1,
  retry_max_duration_secs: 10,
  timeout_secs: 30
) %>

[sinks.new_relic_logs.options.license_key]
type = "string"
common = true
examples = ["xxxx", "${LICENSE_KEY_ENV_VAR}"]
description = "Your New Relic license key (if applicable)."

[sinks.new_relic_logs.options.insert_key]
type = "string"
common = true
examples = ["xxxx", "${INSERT_KEY_ENV_VAR}"]
description = "Your New Relic insert key (if applicable)."

[sinks.new_relic_logs.options.region]
type = "string"
common = true
default = "us"
description = "The API region to send logs to."

[sinks.new_relic_logs.options.region.enum]
us = "The US region"
eu = "The EU region"

<%= render("_partials/fields/_encoding_options.toml",
  namespace: "sinks.new_relic_logs.options",
  encodings: ["json"],
  default: "json"
) %>
