[sinks.papertrail]
title = "Papertrail"
beta = true
common = false
delivery_guarantee = "best_effort"
egress_method = "streaming"
function_category = "transmit"
healthcheck = true
input_types = ["log"]
requirements = {}
write_to_description = "[Papertrail](https://www.papertrail.com/) via [Syslog](https://help.papertrailapp.com/kb/how-it-works/http-api/#submitting-log-messages)"

<%= render("_partials/fields/_component_options.toml", type: "sink", name: "papertrail") %>

<%= render("_partials/fields/_buffer_options.toml", namespace: "sinks.papertrail.options") %>

<%= render("_partials/fields/_encoding_options.toml",
  namespace: "sinks.papertrail.options",
  encodings: ["json", "text"],
) %>

[sinks.papertrail.options.endpoint]
type = "string"
common = true
required = true
examples = ["logs.papertrailapp.com:12345"]
description = "The endpoint to stream logs to."
