[sinks.prometheus]
beta = true
buffer = false
common = true
delivery_guarantee = "best_effort"
egress_method = "exposing"
function_category = "transmit"
healthcheck = false
input_types = ["metric"]
write_to_description = "[Prometheus][urls.prometheus] metrics service"

[sinks.prometheus.options.address]
type = "string"
common = true
examples = ["0.0.0.0:9598"]
null = false
description = "The address to expose for scraping."

[sinks.prometheus.options.namespace]
type = "string"
common = true
examples = ["service"]
null = false
description = """\
A prefix that will be added to all metric names.
It should follow Prometheus [naming conventions][urls.prometheus_metric_naming].\
"""

[sinks.prometheus.options.buckets]
type = "[float]"
default = [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0]
null = false
unit = "seconds"
description = """\
Default buckets to use for [histogram][docs.data-model.metric#histogram] metrics.\
"""

[[sinks.prometheus.output.examples]]
label = "Histograms"
body = """\
Given the following histogram metric events:

```json
[
  {
    "histogram": {
      "name": "response_time_s",
      "val": 0.243
    }
  },
  {
    "histogram": {
      "name": "response_time_s",
      "val": 0.546
    }
  }
]
```

This sink will output the following:

```text
# HELP response_time_s response_time_s
# TYPE response_time_s histogram
response_time_s_bucket{le="0.005"} 0
response_time_s_bucket{le="0.01"} 1
response_time_s_bucket{le="0.025"} 0
response_time_s_bucket{le="0.05"} 1
response_time_s_bucket{le="0.1"} 0
response_time_s_bucket{le="0.25"} 0
response_time_s_bucket{le="0.5"} 0
response_time_s_bucket{le="1.0"} 0
response_time_s_bucket{le="2.5"} 0
response_time_s_bucket{le="5.0"} 0
response_time_s_bucket{le="10.0"} 0
response_time_s_bucket{le="+Inf"} 0
response_time_s_sum 0.789
response_time_s_count 2
```\
"""

[[sinks.prometheus.output.examples]]
label = "Counters"
body = """
Given the following counter metric events:

```json
[
  {
    "counter": {
      "name": "logins",
      "val": 1
    }
  },
  {
    "counter": {
      "name": "logins",
      "val": 3
    }
  }
]

This sink will output the following:

```text
# HELP logins logins
# TYPE logins counter
logins 4
```\
"""

[[sinks.prometheus.output.examples]]
label = "Gauges"
body = """\
Given the following gauge metric events:

```json
[
  {
    "gauge": {
      "name": "memory_rss",
      "val": 250,
      "direction": "plus"
    }
  },
  {
    "gauge": {
      "name": "memory_rss",
      "val": 25
      "direction": "minus"
    }
  }
]
```

This sink will output the following:

```text
# HELP memory_rss memory_rss
# TYPE memory_rss gauge
memory_rss 225
```\
"""