[sinks.pulsar]
title = "Apache Pulsar"
noun = "Apache Pulsar"
beta = true
common = false
delivery_guarantee = "at_least_once"
description = """\
[Pulsar][urls.pulsar] is a multi-tenant, high-performance solution for \
server-to-server messaging. Pulsar was originally developed by Yahoo, it is \
under the stewardship of the Apache Software Foundation. It is an excellent \
tool for streaming logs and metrics data.\
"""
egress_method = "streaming"
features = [
  "Send logs to Apache Pulsar.",
  "Stream data in a real-time fashion.",
  "Automatically retry failed requests, with backoff.",
]
function_category = "transmit"
healthcheck = true
input_types = ["log"]
requirements = {}
write_to_description = "[Apache Pulsar][urls.pulsar] via the [Pulsar protocol][urls.pulsar_protocol]"

<%= render("_partials/fields/_component_options.toml", type: "sink", name: "pulsar") %>

<%= render("_partials/fields/_encoding_options.toml",
  namespace: "sinks.pulsar.options",
  encodings: ["json", "text"]
) %>

[sinks.pulsar.options.address]
type = "string"
common = true
examples = ["127.0.0.1:6650"]
required = true
description = "A host and port pair that the pulsar client should connect to."

[sinks.pulsar.options.topic]
type = "string"
common = true
examples = ["topic-1234"]
required = true
description = "The Pulsar topic name to write events to."

[sinks.pulsar.options.auth]
type = "table"
common = false
description = "Options for the authentication strategy."

[sinks.pulsar.options.auth.children.name]
type = "string"
examples = ["${PULSAR_NAME}", "name123"]
required = false
description = "The basic authentication name."

[sinks.pulsar.options.auth.children.token]
type = "string"
examples = ["${PULSAR_TOKEN}", "123456789"]
required = false
description = "The basic authentication password."
