[sinks.sematext]
title = "Sematext"
batch_max_size = 10490000
batch_timeout_secs = 1
beta = true
buffer = true
common = false
delivery_guarantee = "best_effort"
egress_method = "batching"
function_category = "transmit"
healthcheck = true
input_types = ["log"]
request_rate_limit_duration_secs = 1
request_rate_limit_num = 5
request_retry_attempts = 5
request_retry_initial_backoff_secs = 1
request_retry_max_duration_secs = 10
request_in_flight_limit = 5
request_timeout_secs = 60
write_to_description = "[Sematext][urls.sematext] via the [Elasticsearch API][urls.sematext_es]"

[sinks.sematext.options.region]
type = "string"
required = false
examples = ["na", "eu"]
description = "The region destination to send logs to. This option is required if `host` is not set."

[sinks.sematext.options.host]
type = "string"
required = false
examples = ["http://127.0.0.1", "http://example.com"]
description = "The host that will be used to send logs to. This option is required if `region` is not set."

[sinks.sematext.options.token]
type = "string"
required = true
examples = ["some-sematext-token"]
description = "The token that will be used to write to Sematext."
