[sinks.socket]
title = "Socket"
beta = false
common = true
delivery_guarantee = "best_effort"
egress_method = "streaming"
function_category = "transmit"
healthcheck = true
input_types = ["log"]
requirements = {}
write_to_description = "a socket, such as a TCP or Unix domain socket"

<%= render("_partials/fields/_component_options.toml", type: "sink", name: "socket") %>

<%= render(
  "_partials/fields/_buffer_options.toml",
  namespace: "sinks.socket.options",
  common: false,
  groups: ["tcp", "unix"]
) %>

<%= render("_partials/fields/_encoding_options.toml",
  namespace: "sinks.socket.options",
  encodings: ["json", "text"],
  groups: ["tcp", "unix"]
) %>

[sinks.socket.options.mode]
type = "string"
common = true
groups = ["tcp", "unix"]
required = true
description = "The type of socket to use."

[sinks.socket.options.mode.enum]
tcp = "TCP Socket."
unix = "Unix Domain Socket."

[sinks.socket.options.address]
type = "string"
common = true
examples = ["92.12.333.224:5000"]
groups = ["tcp"]
relevant_when = {mode = "tcp"}
required = true
description = "The address to connect to. The address _must_ include a port."

[sinks.socket.options.path]
type = "string"
common = true
examples = ["/path/to/socket"]
groups = ["unix"]
relevant_when = {mode = "unix"}
required = true
description = """The unix socket path. This should be the absolute path.\
"""

<%= render(
  "_partials/fields/_tls_connector_options.toml",
  namespace: "sinks.socket.options",
  can_enable: true,
  can_verify_certificate: true,
  can_verify_hostname: true,
  groups: ["tcp"]
) %>

