[sinks.splunk_hec]
title = "Splunk HEC"
batch_max_size = 1049000
batch_timeout_secs = 1
buffer = true
common = true
delivery_guarantee = "at_least_once"
egress_method = "batching"
encodings = ["ndjson", "text"]
function_category = "transmit"
healthcheck = true
input_types = ["log"]
request_rate_limit_duration_secs = 1
request_rate_limit_num =10
request_retry_attempts = 5
request_retry_initial_backoff_secs = 1
request_retry_max_duration_secs = 10
request_in_flight_limit = 10
request_timeout_secs = 60
service_providers = ["Splunk"]
write_to_description = "a [Splunk's HTTP Event Collector][urls.splunk_hec]"
tls_options = []

[sinks.splunk_hec.options.host]
type = "string"
common = true
examples = ["my-splunk-host.com"]
required = true
description = "Your Splunk HEC host."

[sinks.splunk_hec.options.token]
type = "string"
common = true
examples = ["${TOKEN_ENV_VAR}", "A94A8FE5CCB19BA61C4C08"]
required = true
description = "Your Splunk HEC token."
