[sinks.splunk_hec]
title = "Splunk HEC"
beta = false
common = true
delivery_guarantee = "at_least_once"
egress_method = "batching"
function_category = "transmit"
healthcheck = true
input_types = ["log"]
requirements = {}
service_providers = ["Splunk"]
write_to_description = "a [Splunk's HTTP Event Collector][urls.splunk_hec]"

<%= render("_partials/fields/_component_options.toml", type: "sink", name: "splunk_hec") %>

<%= render("_partials/fields/_batch_options.toml", namespace: "sinks.splunk_hec.options", common: false, max_events: nil, max_size: 1049000, timeout_secs: 1) %>

<%= render(
  "_partials/fields/_buffer_options.toml",
  namespace: "sinks.splunk_hec.options",
  common: false
) %>

<%= render(
  "_partials/fields/_request_options.toml",
  namespace: "sinks.splunk_hec.options",
  common: false,
  in_flight_limit: 10,
  rate_limit_duration_secs: 1,
  rate_limit_num: 10,
  retry_attempts: -1,
  retry_initial_backoff_secs: 1,
  retry_max_duration_secs: 10,
  timeout_secs: 60
) %>

<%= render("_partials/fields/_encoding_options.toml",
  namespace: "sinks.splunk_hec.options",
  encodings: ["json", "text"]
) %>

[sinks.splunk_hec.options.host]
type = "string"
common = true
examples = ["http://my-splunk-host.com"]
required = true
description = "Your Splunk HEC host."

[sinks.splunk_hec.options.host_key]
type = "string"
common = true
examples = ["hostname"]
required = false
description = """\
The name of the log field to be used as the hostname sent to Splunk HEC. This overrides the \
[global `host_key` option][docs.reference.global-options#host_key].\
"""

[sinks.splunk_hec.options.token]
type = "string"
common = true
examples = ["${TOKEN_ENV_VAR}", "A94A8FE5CCB19BA61C4C08"]
required = true
description = "Your Splunk HEC token."

[sinks.splunk_hec.options.indexed_fields]
type = "[string]"
common = true
examples = [["field1", "field2"]]
relevant_when = {encoding = "json"}
required = false
description = "Fields to be [added to Splunk index][urls.splunk_hec_indexed_fields]."

<%= render("_partials/fields/_tls_connector_options.toml", namespace: "sinks.splunk_hec.options", can_enable: false, can_verify_certificate: true, can_verify_hostname: false) %>
