[sinks.statsd]
title = "Statsd"
beta = true
common = false
delivery_guarantee = "best_effort"
egress_method = "streaming"
function_category = "transmit"
healthcheck = false
requirements = {}
input_types = ["metric"]
write_to_description = "[StatsD][urls.statsd] metrics service"

<%= render("_partials/fields/_component_options.toml", type: "sink", name: "statsd") %>

[sinks.statsd.options.address]
type = "string"
common = true
examples = ["127.0.0.1:8125"]
default = "127.0.0.1:8125"
description = "The UDP socket address to send stats to."

[sinks.statsd.options.namespace]
type = "string"
common = true
examples = ["service"]
required = true
description = "A prefix that will be added to all metric names."

[[sinks.statsd.output.examples]]
label = "Generic"
body = """\
```text
gorets:1|c\nglork:320|ms\ngaugor:333|g\nuniques:765|s
```\
"""
