[sinks.tcp]
title = "TCP"
buffer = true
common = false
delivery_guarantee = "best_effort"
egress_method = "streaming"
encodings = ["json", "text"]
function_category = "transmit"
healthcheck = true
input_types = ["log"]
write_to_description = "a TCP connection"
tls_options = ["+enabled"]

[sinks.tcp.options.address]
type = "string"
common = true
examples = ["92.12.333.224:5000"]
null = false
description = "The TCP address."