edition = "2021"
newline_style = "unix"
reorder_imports = true

# Nightly only features
# unstable_features = true
# imports_granularity = "Crate"
# group_imports = "StdExternalCrate"
# indent_style = "Block"
