[advisories]
ignore = [
    "RUSTSEC-2020-0014", # Advisory for dev dependency of `trust-dns` for testing
                         # dns servers.
    "RUSTSEC-2020-0002", # tracked in #1639
    "RUSTSEC-2020-0001", # dev dependency only
]
