[licenses]
unlicensed = "deny"
default = "deny"
copyleft = "deny"
allow = [
  "0BSD",
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "BSL-1.0",
  "CC0-1.0",
  "ISC",
  "MIT",
  "OpenSSL",
  "Unicode-DFS-2016",
  "Zlib"
]

private = { ignore = true }

exceptions = [
    # MPL-2.0 are added case-by-case to make sure we are in compliance. To be in
    # compliance we cannot be modifying the source files.
    { allow = ["MPL-2.0"], name = "colored", version = "*" },
    { allow = ["MPL-2.0"], name = "webpki-roots", version = "*" },
    { allow = ["MPL-2.0"], name = "vector-config-common", version = "*" },
    { allow = ["MPL-2.0"], name = "vector-config-macros", version = "*" },
    { allow = ["MPL-2.0"], name = "vrl", version = "*" },
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[advisories]
ignore = [
    # Vulnerability in `rsa` crate: https://rustsec.org/advisories/RUSTSEC-2023-0071.html
    # There is not fix available yet.
    # https://github.com/vectordotdev/vector/issues/19262
    "RUSTSEC-2023-0071"
]
