[licenses]
allow = [
  "MIT",
  "CC0-1.0",
  "ISC",
  "OpenSSL",
  "Unlicense",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "Zlib",
]

unlicensed = "warn"
default = "warn"

private = { ignore = true }

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[advisories]
ignore = [
    # `net2` crate has been deprecated; use `socket2` instead
    "RUSTSEC-2020-0016",
    # failure: failure is officially deprecated/unmaintained
    "RUSTSEC-2020-0036",
    # stdweb is unmaintained
    # can be removed after next release of time
    # https://github.com/time-rs/time/commit/8b2734351a5cd05a9bd3315f1af76c28b5852fec
    "RUSTSEC-2020-0056",
    # ordered_flat - can be removed when heim next releases their beta branch
    "RUSTSEC-2020-0082",
    # lucet-runtime-internals - we'll need to upgrade here
    "RUSTSEC-2020-0004",
]
