# This is a part of our skaffold setup for development.
# Do not use in production.
# If you're looking for a way to deploy vector, see `distribution/kubernetes`
# and `distribution/helm` directories, and our documentation on the website.

namespace: vector

bases:
  - distribution/kubernetes

resources:
  - skaffold/manifests/namespace.yaml
  - skaffold/manifests/config.yaml

patchesStrategicMerge:
  - skaffold/manifests/patches/env.yaml
