[build]
base = "website"
publish = "public"

# Reinstate this when we figure out how to target this better
#ignore = "./scripts/build-ignore.sh"

[build.environment]
HUGO_VERSION = "0.84.0"
ALGOLIA_INDEX_FILE="public/search.json"

[context.production]
command = "make ci-production-build"

[context.production.environment]
ALGOLIA_INDEX_NAME="vector_docs_prod"

[context.deploy-preview]
command = "make ci-preview-build"

[context.deploy-preview.environment]
ALGOLIA_INDEX_NAME="vector_docs_staging"

[context.branch-deploy]
command = "make ci-preview-build"

[context.branch-deploy.environment]
ALGOLIA_INDEX_NAME="vector_docs_staging"

# Subdomain redirects
[[redirects]]
from = "https://vector-project.netlify.com/*"
to = "https://vector.dev/:splat"
status = 301
force = true

[[redirects]]
from = "https://calendar.vector.dev/*"
to = "https://calendar.google.com/calendar/embed?src=c_qsq1nrsgetsspkn7pjrqh6cclc%40group.calendar.google.com&ctz=America%2FNew_York"
status = 302
force = true

[[redirects]]
from = "https://chat.vector.dev/*"
to = "https://discord.gg/dX3bdkF"
status = 302
force = true

[[redirects]]
from = "https://discussions.vector.dev/*"
to = "https://github.com/timberio/vector/discussions"
status = 302
force = true

[[redirects]]
from = "https://roadmap.vector.dev/*"
to = "https://airtable.com/shriTZW5LeOE4cIyJ"
status = 302
force = true

[[redirects]]
from = "https://sh.vector.dev/*"
to = "http://sh.vector.dev.s3-website-us-east-1.amazonaws.com/:splat"
status = 200
force = true

[[redirects]]
from = "https://test-results.vector.dev/*"
to = "http://test-results.vector.dev.s3-website-us-east-1.amazonaws.com/:splat"
status = 200
force = true

[[redirects]]
from = "https://rustdoc.vector.dev/*"
to = "https://vector-rustdoc.netlify.app/vector/:splat"
status = 301
force = true
