# `file` Source Example
# ------------------------------------------------------------------------------
# A simple example demonstrating the `file` source
# Docs: https://docs.vectorproject.io/usage/configuration/sources/file

[sources.my_file_source]
  # REQUIRED - General
  type = "file" # must be: file
  exclude = ["/var/log/nginx*.log"]
  include = ["/var/log/nginx*.log"]

  # OPTIONAL - General
  ignore_older = 86400 # no default, seconds
  max_line_bytes = 102400 # default, bytes
  start_at_beginning = false # default

  # OPTIONAL - Context
  file_key = "file" # default
  host_key = "host" # default
