# `syslog` Source Example
# ------------------------------------------------------------------------------
# A simple example demonstrating the `syslog` source
# Docs: https://docs.vectorproject.io/usage/configuration/sources/syslog

[sources.my_syslog_source]
  # REQUIRED - General
  type = "syslog" # must be: syslog

  # OPTIONAL - General
  address = "0.0.0.0:9000" # no default
  max_length = 102400 # default, bytes
  mode = "tcp" # no default, enum: tcp, udp, unix
  path = "/path/to/socket" # no default

  # OPTIONAL - Context
  host_key = "host" # default
