version: '3'

services:
  opentelemetry-collector:
    image: docker.io/otel/opentelemetry-collector-contrib:${CONFIG_VERSION}
    volumes:
    - ../../../tests/data/opentelemetry/config.yaml:/etc/otelcol-contrib/config.yaml
