version: '3'

services:
  mock-ec2-metadata:
    image: public.ecr.aws/aws-ec2/amazon-ec2-metadata-mock:v1.11.2
  mock-localstack:
    image: docker.io/localstack/localstack-full:0.11.6
    environment:
    - SERVICES=kinesis,s3,cloudwatch,elasticsearch,es,firehose,sqs
  mock-watchlogs:
    image: docker.io/luciofranco/mockwatchlogs:latest
  mock-ecs:
    image: docker.io/amazon/amazon-ecs-local-container-endpoints:latest
    volumes:
    - $DOCKER_SOCKET:/var/run/docker.sock
    - $HOME/.aws/:/home/.aws/
