# `aws_s3` Sink Example
# ------------------------------------------------------------------------------
# A simple example demonstrating the `aws_s3` sink
# Docs: https://docs.vector.dev/usage/configuration/sinks/aws_s3

[sinks.my_aws_s3_sink]
  # REQUIRED - General
  type = "aws_s3" # must be: aws_s3
  inputs = ["my-source-id"]
  bucket = "my-bucket"
  region = "us-east-1"

  # OPTIONAL - Batching
  batch_size = 10490000 # default, bytes
  batch_timeout = 300 # default, bytes

  # OPTIONAL - Object Names
  filename_append_uuid = true # default
  filename_time_format = "%s" # default
  key_prefix = "date=%F/" # default

  # OPTIONAL - Requests
  compression = "gzip" # no default, must be: gzip
  encoding = "ndjson" # no default, enum: ndjson, text
  gzip = false # default
  rate_limit_duration = 1 # default, seconds
  rate_limit_num = 5 # default
  request_in_flight_limit = 5 # default
  request_timeout_secs = 30 # default, seconds
  retry_attempts = 5 # default
  retry_backoff_secs = 5 # default, seconds

  # OPTIONAL - Buffer
  [sinks.my_aws_s3_sink.buffer]
    type = "memory" # default, enum: memory, disk
    when_full = "block" # default, enum: block, drop_newest
    max_size = 104900000 # no default
    num_items = 500 # default
