# `aws_kinesis_streams` Sink Example
# ------------------------------------------------------------------------------
# A simple example demonstrating the `aws_kinesis_streams` sink
# Docs: https://docs.vector.dev/usage/configuration/sinks/aws_kinesis_streams

[sinks.my_aws_kinesis_streams_sink]
  # REQUIRED - General
  type = "aws_kinesis_streams" # must be: aws_kinesis_streams
  inputs = ["\"my-source-id\""]
  region = "us-east-1"
  stream_name = "my-stream"

  # OPTIONAL - Batching
  batch_size = 1049000 # default, bytes
  batch_timeout = 1 # default, bytes

  # OPTIONAL - Requests
  encoding = "json" # no default, enum: json, text
  rate_limit_duration = 1 # default, seconds
  rate_limit_num = 5 # default
  request_in_flight_limit = 5 # default
  request_timeout_secs = 30 # default, seconds
  retry_attempts = 5 # default
  retry_backoff_secs = 5 # default, seconds

  # OPTIONAL - Buffer
  [sinks.my_aws_kinesis_streams_sink.buffer]
    type = "memory" # default, enum: memory, disk
    when_full = "block" # default, enum: block, drop_newest
    max_size = 104900000 # no default
    num_items = 500 # default
