# `kafka` Sink Example
# ------------------------------------------------------------------------------
# A simple example demonstrating the `kafka` sink
# Docs: https://docs.vector.dev/usage/configuration/sinks/kafka

[sinks.my_kafka_sink]
  # REQUIRED - General
  type = "kafka" # must be: kafka
  inputs = ["\"my-source-id\""]
  bootstrap_servers = "10.14.22.123:9092,10.14.23.332:9092"
  topic = "topic-1234"

  # OPTIONAL - General
  encoding = "json" # no default, enum: json, text
  key_field = "partition_key" # no default

  # OPTIONAL - Buffer
  [sinks.my_kafka_sink.buffer]
    type = "memory" # default, enum: memory, disk
    when_full = "block" # default, enum: block, drop_newest
    max_size = 104900000 # no default
    num_items = 500 # default
