version: '3'

services:
  dufs:
    image: docker.io/sigoden/dufs:${CONFIG_VERSION}
    command:
    - /data
    volumes:
    - ../../../tests/data/http-client/serve:/data
  dufs-auth:
    image: docker.io/sigoden/dufs:${CONFIG_VERSION}
    command:
    - -a
    - "user:pass@/"
    - --auth-method
    - basic
    - /data
    volumes:
    - ../../../tests/data/http-client/serve:/data
  dufs-https:
    image: docker.io/sigoden/dufs:${CONFIG_VERSION}
    command:
    - --tls-cert
    - /certs/ca.cert.pem
    - --tls-key
    - /certs/ca.key.pem
    - /data
    volumes:
    - ../../../tests/data/http-client/serve:/data
    - ../../../tests/data/ca/intermediate_server/certs/dufs-https-chain.cert.pem:/certs/ca.cert.pem
    - ../../../tests/data/ca/intermediate_server/private/dufs-https.key.pem:/certs/ca.key.pem
