[data_model.metric.schema.kind]
type = "string"
required = true
description = """\
The metric value kind. This determines how the value is merged downstream if \
metrics are aggregated.
"""

[data_model.metric.schema.kind.enum]
absolute = "The value is an absolute, stand-alone value. It can be used individually."
incremental = "The value is incremental and is used to form a holistic value by merging with other incremental values. Individually it does not tell the whole story."

[data_model.metric.schema.name]
type = "string"
examples = ["login.count", "response_time"]
required = true
description = """\
The metric name.\
"""

[data_model.metric.schema.tags]
type = "map"
examples = [{host = "my.host.com"}]
required = true
description = """\
Tags that add additional metadata or context to the metric. These are simple \
key/value pairs in `string` format and cannot be nested.\
"""

[data_model.metric.schema.timestamp]
type = "timestamp"
examples = ["2019-11-01T21:15:47.443232Z"]
required = true
description = """\
The metric timestamp, representing when the metric was created/ingested within \
Vector.\
"""

[data_model.metric.schema.counter]
type = "struct"
description = """\
A single value that can _only_ be incremented or reset to zero value, it \
cannot be decremented.\
"""

[data_model.metric.schema.counter.children.value]
type = "double"
examples = [2.6, 5.0]
required = true
description = """\
The value to increment the counter by. Can only be positive.\
"""


[data_model.metric.schema.gauge]
type = "struct"
description = """\
A gauge represents a point-in-time value that can increase and decrease. \
Vector's internal gauge type represents changes to that value. Gauges should be \
used to track fluctuations in values, like current memory or CPU usage.\
"""

[data_model.metric.schema.gauge.children.value]
type = "double"
examples = [554222.0]
required = true
description = """\
A specific point-in-time value for the gauge.\
"""

[data_model.metric.schema.set]
type = "struct"
description = """\
A set represents a count of unique values, AKA the cardinality.\
"""

[data_model.metric.schema.set.children.values]
type = "[string]"
examples = [["unique item 1", "unique item 2"]]
required = true
description = """\
The list of unique values.\
"""


[data_model.metric.schema.distribution]
type = "struct"
description = """\
A distribution represents a distribution of sampled values.\
"""

[data_model.metric.schema.distribution.children.values]
type = "[double]"
examples = [[12.0, 43.3, 25.2]]
required = true
description = """\
The list of values contained within the distribution.\
"""

[data_model.metric.schema.distribution.children.sample_rates]
type = "[uint]"
examples = [[12, 43, 25]]
required = true
description = """\
The rate at which each individual value was sampled.\
"""

[data_model.metric.schema.distribution.children.statistic]
type = "string"
examples = ["histogram","summary"]
required = true
description = """\
Statistic to be applied on the samples.\
"""


[data_model.metric.schema.aggregated_histogram]
type = "struct"
description = """\
Also called a "timer". A `aggregated_histogram` samples observations (usually \
things like request durations or response sizes) and counts them in \
configurable buckets. It also provides a sum of all observed values.\
"""

[data_model.metric.schema.aggregated_histogram.children.buckets]
type = "[double]"
examples = [[1, 2, 5, 10, 25]]
required = true
description = """\
The buckets contained within this histogram.\
"""

[data_model.metric.schema.aggregated_histogram.children.counts]
type = "[uint]"
examples = [[1, 5, 25, 2, 5]]
required = true
description = """\
The number of values contained within each bucket.\
"""

[data_model.metric.schema.aggregated_histogram.children.count]
type = "uint"
examples = [54]
required = true
description = """\
The total number of values contained within the histogram.\
"""

[data_model.metric.schema.aggregated_histogram.children.sum]
type = "double"
examples = [524.0]
required = true
description = """\
The sum of all values contained within the histogram.\
"""


[data_model.metric.schema.aggregated_summary]
type = "struct"
description = """\
Similar to a histogram, a summary samples observations (usually things like \
request durations and response sizes). While it also provides a total count \
of observations and a sum of all observed values, it calculates configurable \
quantiles over a sliding time window.
"""

[data_model.metric.schema.aggregated_summary.children.quantiles]
type = "[double]"
examples = [[0.1, 0.5, 0.75, 1.0]]
required = true
description = """\
The quantiles contained within the summary, where 0 ≤ quantile ≤ 1.\
"""

[data_model.metric.schema.aggregated_summary.children.values]
type = "[double]"
examples = [[2.1, 4.68, 23.02, 120.1]]
required = true
description = """\
The values contained within the summary that align with the `quantiles`.\
"""

[data_model.metric.schema.aggregated_summary.children.count]
type = "uint"
examples = [54]
required = true
description = """\
The total number of values contained within the summary.\
"""

[data_model.metric.schema.aggregated_summary.children.sum]
type = "double"
examples = [524.0]
required = true
description = """\
The sum of all values contained within the summary.\
"""
