apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-agent-config
data:
  vector.toml: |
    [sinks.stdout]
        type = "console"
        inputs = ["kubernetes_logs", "internal_metrics"]
        target = "stdout"
        encoding = "json"
