# Parsing logs as metrics and sending to CloudWatch
# ------------------------------------------------------------------------------
# WIP

data_dir = "/var/lib/vector"

# Ingest
[sources.file]
type = "file"
include = ["sample.log"]
start_at_beginning = true

# Structure and parse the data
[transforms.regex_parser]
inputs = ["file"]
type = "regex_parser"
regex = '^(?P<host>[\w\.]+) - (?P<user>[\w-]+) \[(?P<timestamp>.*)\] "(?P<method>[\w]+) (?P<path>.*)" (?P<status>[\d]+) (?P<bytes_out>[\d]+)$'

# Transform into metrics
[transforms.log_to_metric]
inputs = ["regex_parser"]
type = "log_to_metric"

[[transforms.log_to_metric.metrics]]
type = "counter"
increment_by_value = true
field = "bytes_out"

# Output data
[sinks.console_metrics]
inputs = ["log_to_metric"]
type = "console"

[sinks.console_logs]
inputs = ["regex_parser"]
type = "console"

[sinks.cloudwatch]
inputs = ["log_to_metric"]
type = "aws_cloudwatch_metrics"
namespace = "vector"
endpoint = "http://localhost:4582"
