apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "libvector.fullname" . }}
  labels:
    {{- include "libvector.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "libvector.fullname" . }}
  selector:
    matchLabels:
      {{- include "libvector.selectorLabels" . | nindent 6 }}
  podManagementPolicy: "{{ .Values.podManagementPolicy }}"
  replicas: {{ .Values.replicas }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "libvector.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "libvector.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: vector
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ include "libvector.imageTag" . }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          args:
            - --config
            - /etc/vector/*.toml
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            # Vector data dir mount.
            - name: data-dir
              mountPath: "{{ .Values.globalOptions.dataDir }}"
            # Vector config dir mount.
            - name: config-dir
              mountPath: /etc/vector
              readOnly: true
            # Extra volumes.
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      terminationGracePeriodSeconds: 60
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        # Vector will store it's data here.
        - name: data-dir
        {{- if eq .Values.storage.mode "managedPersistentVolumeClaim" }}
          persistentVolumeClaim:
            claimName: {{ include "libvector.fullname" $ }}-data-dir
        {{- else if eq .Values.storage.mode "existingPersistentVolumeClaim" }}
          persistentVolumeClaim:
            claimName: {{ required "The value storage.existingPersistentVolumeClaim must be set" .Values.storage.existingPersistentVolumeClaim }}
        {{- else if eq .Values.storage.mode "hostPath" }}
          hostPath:
            path: {{ required "The value storage.hostPath must be set" .Values.storage.hostPath | quote }}
        {{- else if eq .Values.storage.mode "empty" }}
          emptyDir: {}
        {{- else }}
        {{ fail "Please provide a valid storage.mode value" }}
        {{- end }}
        # Vector config dir with a managed config map.
        - name: config-dir
          configMap:
            name: {{ include "libvector.configMapName" . }}
        # Extra volumes.
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- if eq .Values.storage.mode "managedPersistentVolumeClaim" }}
{{- with .Values.storage.managedPersistentVolumeClaim }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "libvector.fullname" $ }}-data-dir
        labels:
        {{- include "libvector.labels" $ | nindent 10 }}
        {{- with .labels }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .annotations }}
        annotations: {{- toYaml . | nindent 10 }}
      {{- end }}
      spec:
        accessModes: ["ReadWriteOnce"]
      {{- with .storageClass }}
      {{- if (eq "-" .) }}
        storageClassName: ""
      {{- else }}
        storageClassName: {{ . | quote}}
      {{- end }}
      {{- end }}
        resources:
          requests:
            storage: {{ .size | quote }}
{{- end }}
{{- end }}
