apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "libvector.fullname" . }}
  labels:
    {{- include "libvector.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "libvector.fullname" . }}-headless
  selector:
    matchLabels:
      {{- include "libvector.selectorLabels" . | nindent 6 }}
  podManagementPolicy: "{{ .Values.podManagementPolicy }}"
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      annotations:
        {{- if not .Values.externalConfigMap }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- include "libvector.rollmeAnnotation" . | nindent 8 }}
        {{- include "libvector.metricsPrometheusPodAnnotations" . | nindent 8 }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "libvector.selectorLabels" . | nindent 8 }}
        vector.dev/exclude: "true"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "libvector.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: vector
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "libvector.image" . | quote }}
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          args:
            - --config
            - /etc/vector/*.toml
          env:
            {{- include "libvector.globalEnv" . | nindent 12 }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            {{- include "libvector.metricsContainerPorts" . | nindent 12  }}
            {{- with .Values.extraContainersPorts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            # Vector data dir mount.
            - name: data-dir
              mountPath: "{{ .Values.globalOptions.dataDir }}"
            # Vector config dir mount.
            - name: config-dir
              mountPath: /etc/vector
              readOnly: true
            # Extra volumes.
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      terminationGracePeriodSeconds: 60
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if ne .Values.storage.mode "managedPersistentVolumeClaim" }}
        # Vector will store it's data here.
        - name: data-dir
        {{- if eq .Values.storage.mode "existingPersistentVolumeClaim" }}
          persistentVolumeClaim:
            claimName: {{ required "The value storage.existingPersistentVolumeClaim must be set" .Values.storage.existingPersistentVolumeClaim }}
        {{- else if eq .Values.storage.mode "hostPath" }}
          hostPath:
            path: {{ required "The value storage.hostPath must be set" .Values.storage.hostPath | quote }}
        {{- else if eq .Values.storage.mode "empty" }}
          emptyDir: {}
        {{- else }}
        {{ fail "Please provide a valid storage.mode value" }}
        {{- end }}
        {{- end }}
        # Vector config dir.
        - name: config-dir
          projected:
            sources:
              - configMap:
                  name: {{ include "libvector.configMapName" . }}
                  optional: true
              {{- with .Values.extraConfigDirSources }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
        {{- with .Values.extraVolumes }}
        # Extra volumes.
        {{- toYaml . | nindent 8 }}
        {{- end }}
  volumeClaimTemplates:
    {{- if eq .Values.storage.mode "managedPersistentVolumeClaim" }}
    {{- with .Values.storage.managedPersistentVolumeClaim }}
    # Vector will store it's data here.
    - metadata:
        name: data-dir
        labels:
          {{- include "libvector.labels" $ | nindent 10 }}
          {{- with .labels }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        annotations:
          {{- with .annotations }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
      spec:
        accessModes: ["ReadWriteOnce"]
      {{- with .storageClass }}
      {{- if (eq "-" .) }}
        storageClassName: ""
      {{- else }}
        storageClassName: {{ . | quote}}
      {{- end }}
      {{- end }}
        resources:
          requests:
            storage: {{ .size | quote }}
    {{- end }}
    {{- end }}
