version: '3'

services:
  beats-heartbeat:
    image: docker.elastic.co/beats/heartbeat:${CONFIG_VERSION}
    command: -environment=container -strict.perms=false
    volumes:
    - ../../../tests/data/logstash/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro
  logstash:
    image: docker.elastic.co/logstash/logstash:7.13.1
    volumes:
    - /dev/null:/usr/share/logstash/pipeline/logstash.yml
    - ../../../tests/data/host.docker.internal.crt:/tmp/logstash.crt
    - ../../../tests/data/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
