[transforms.ansi_stripper]
title = "ANSI Stripper"
allow_you_to_description = "strips ANSI characters from the specified field"
beta = false
common = false
function_category = "sanitize"
input_types = ["log"]
output_types = ["log"]

[transforms.ansi_stripper.options.field]
type = "string"
common = true
default = "message"
required = true
description = "The target field to strip ANSI characters from."
