[transforms.concat]
title = "Concat"
allow_you_to_description = "concat (substrings) of other fields to a new one"
beta = true
function_category = ["filter"]
input_types = ["log"]
output_types = ["log"]
resources = []

[transforms.concat.options.target]
type = "string"
examples = ["dest_field_name"]
required = true
description = """\
The name for the new label.\
"""

[transforms.concat.options.joiner]
type = "string"
default = " "
examples = [" ", ",", "_", "+"]
required = true
description = """\
The string that is used to join all items.\
"""

[transforms.concat.options.items]
type = "[string]"
examples = [["fist[..3]", "second[-5..]", "third[3..6]"]]
required = true
description = """\
A list of substring definitons in the format of source_field[start..end]. \
For both start and end negative values are counted from the end of the \
string.\
"""

[[transforms.concat.output.log.examples]]
label = "Generic"
body = """\
Given the following input log event:

```json
{
  "message": "Hello world",
  "month": "12",
  "day": "25",
  "year": "2020"
}
```

And the following example configuration:

```toml
[transforms.concat_date]
  type = "concat"
  items = ["month", "day", "year"]
  target = "date"
  joiner = "/"
```

A log event will be output with the following structure:

```json
{
  "message": "Hello world",
  "date": "12/25/2020", // <-- new field
  "month": "12",
  "day": "25",
  "year": "2020"
}
```\
"""
