[transforms.logfmt_parser]
title = "Logfmt Parser"
allow_you_to_description = """\
extract data from a logfmt-formatted log field\
"""
beta = true
common = true
function_category = "parse"
input_types = ["log"]
output_types = ["log"]
requirements = {}

<%= render("_partials/_component_options.toml", type: "transform", name: "logfmt_parser") %>

[transforms.logfmt_parser.options.field]
type = "string"
common = true
default = "message"
examples = ["message", "parent.child", "array[0]"]
field_path_notation = true
required = true
description = "The log field to parse."

[transforms.logfmt_parser.options.drop_field]
type = "bool"
common = true
default = true
required = true
description = "If the specified `field` should be dropped (removed) after parsing."

<%= render("_partials/_types.toml", namespace: "transforms.logfmt_parser", common: true) %>
