[transforms.lua]
title = "LUA"
allow_you_to_description = "transform events with a full embedded [Lua][urls.lua] engine"
beta = true
common = true
function_category = "program"
input_types = ["log"]
output_types = ["log"]
requirements = {}

<%= render("_partials/_component_options.toml", type: "transform", name: "lua") %>

[transforms.lua.options.source]
type = "string"
common = true
examples = [
"""\
require("script") # a `script.lua` file must be in your `search_dirs`

if event["host"] == nil then
  local f = io.popen ("/bin/hostname")
  local hostname = f:read("*a") or ""
  f:close()
  hostname = string.gsub(hostname, "\\n$", "")
  event["host"] = hostname
end\
"""
]
required = true
description = "The inline Lua source to evaluate."

[transforms.lua.options.search_dirs]
type = "[string]"
examples = [["/etc/vector/lua"]]
common = true
description = """\
A list of directories search when loading a Lua file via the `require` \
function.\
"""

[[transforms.lua.test_examples]]
label = "Basic"
body = """\
[[tests]]
  name = "test_lua"

  [[tests.inputs]]
    insert_at = "my_transform_id"
    type = "raw"
    value = "I desperately want a host please"

  [[tests.outputs]]
    extract_from = "my_transform_id"
    [[tests.outputs.conditions]]
      type = "check_fields"
      "message.eq" = "I desperately want a host please"
      "host.eq" = "myhost"\
"""
