[transforms.sampler]
title = "Sampler"
allow_you_to_description = "sample events with a configurable rate"
beta = true
common = true
function_category = "filter"
input_types = ["log"]
output_types = ["log"]
requirements = {}

<%= render("_partials/fields/_component_options.toml", type: "transform", name: "sampler") %>

[transforms.sampler.options.key_field]
type = "string"
common = false
examples = ["message"]
required = false
description = """\
The name of the log field to use to determine if the event should be passed. \
This defaults to the [global `message_key` option][docs.reference.global-options#message_key].\
"""

[transforms.sampler.options.pass_list]
type = "[string]"
common = true
examples = [["[error]", "field2"]]
description = """\
A list of regular expression patterns to exclude events from sampling. \
If an event's key field (see `key_field`) matches _any_ of these patterns it will \
_not_ be sampled.\
"""

[transforms.sampler.options.rate]
type = "int"
common = true
examples = [10]
required = true
description = """\
The rate at which events will be forwarded, expressed as 1/N. For example, \
`rate = 10` means 1 out of every 10 events will be forwarded and the rest \
will be dropped.\
"""

## TODO: Add regex synax docs?
