[transforms.split]
title = "Split"
allow_you_to_description = """\
split a field's value on a given separator \
and zip the tokens into ordered field names\
"""
common = false
function_category = "parse"
input_types = ["log"]
output_types = ["log"]
types_coercion = true

[transforms.split.options.field]
type = "string"
common = true
default = "message"
required = true
description = "The field to apply the split on."

[transforms.split.options.field_names]
type = "[string]"
common = true
examples = [["timestamp", "level", "message"]]
required = true
description = "The field names assigned to the resulting tokens, in order."

[transforms.split.options.separator]
type = "[string]"
common = true
default = "whitespace"
examples = [","]
required = true
description = """\
The separator to split the field on. \
If no separator is given, it will split on whitespace.\
"""

[transforms.split.options.drop_field]
type = "bool"
common = true
default = true
required = true
description = "If `true` the `field` will be dropped after parsing."
