version: '3'

services:
  splunk-hec:
    image: docker.io/splunk/splunk:${CONFIG_VERSION}
    environment:
    - SPLUNK_START_ARGS=--accept-license
    - SPLUNK_PASSWORD=password
    - SPLUNK_HEC_TOKEN=abcd1234
    volumes:
    - ../../../tests/data/splunk/default.yml:/tmp/defaults/default.yml
    ports:
    - 8000:8000
    - 8088:8088
    - 8089:8089
