# Platforms
#
# Platforms represent higher level abstractions. They are opinionated platforms
# where Vector can be installed.

[installation.platforms.docker]
title = "Docker"
archs = ["x86_64", "ARM64", "ARMv7"]
interfaces = [
  "docker-cli",
  "docker-compose",
]
oss = ["Linux", "MacOS"]
strategies = [
  {name = "daemon", source = "docker"},
  {name = "sidecar", source = "file"},
  {name = "service", source = "vector"},
]

<%= render("_partials/descriptions/_docker.toml") %>
