<%- groups ||= [] -%>
[<%= namespace %>.tls]
type = "table"
category = "TLS"
common = false
groups = <%= groups.to_toml %>
description = "Configures the TLS options for connections from this sink."

<%- if can_enable -%>
[<%= namespace %>.tls.children.enabled]
type = "bool"
common = true
default = false
groups = <%= groups.to_toml %>
sort = 1
description = "Enable TLS during connections to the remote."
<%- end -%>

[<%= namespace %>.tls.children.ca_path]
type = "string"
examples = ["/path/to/certificate_authority.crt"]
groups = <%= groups.to_toml %>
description = """\
Absolute path to an additional CA certificate file, in DER or PEM format \
(X.509).\
"""

[<%= namespace %>.tls.children.crt_path]
type = "string"
common = true
examples = ["/path/to/host_certificate.crt"]
groups = <%= groups.to_toml %>
description = """\
Absolute path to a certificate file used to identify this connection, in DER \
or PEM format (X.509) or PKCS#12. If this is set and is not a PKCS#12 archive, \
`key_path` must also be set.\
"""

[<%= namespace %>.tls.children.key_path]
type = "string"
common = true
examples = ["/path/to/host_certificate.key"]
groups = <%= groups.to_toml %>
description = """\
Absolute path to a certificate key file used to identify this connection, in \
DER or PEM format (PKCS#8). If this is set, `crt_path` must also be set.\
"""

[<%= namespace %>.tls.children.key_pass]
type = "string"
examples = ["${KEY_PASS_ENV_VAR}", "PassWord1"]
groups = <%= groups.to_toml %>
description = """\
Pass phrase used to unlock the encrypted key file. This has no effect unless \
`key_path` is set.\
"""

<%- if can_verify_certificate -%>
[<%= namespace %>.tls.children.verify_certificate]
type = "bool"
default = true
groups = <%= groups.to_toml %>
description = """\
If `true` (the default), Vector will validate the TLS certificate of the \
remote host.\
"""
warnings = [{visibility_level = "option", text = "Setting this to `false` means the certificate will be loaded and checked for validity, but the handshake will not attempt to verify the certificate. Do NOT set this to `false` unless you understand the risks of not verifying the remote certificate."}]
<%- end -%>

<%- if can_verify_hostname -%>
[<%= namespace %>.tls.children.verify_hostname]
type = "bool"
default = true
groups = <%= groups.to_toml %>
description = """\
If `true` (the default), Vector will validate the configured remote host name \
against the remote host's TLS certificate. Do NOT set this to `false` unless \
you understand the risks of not verifying the remote hostname.\
"""
<%- end -%>
