[sources.in]
type = "tcp"
address = "127.0.0.1:1235"

[transforms.sampler]
type = "sampler"
inputs = ["in"]
rate = 10
pass_list = ["error"]

[sinks.out]
type = "tcp"
inputs = ["sampler"]
address = "127.0.0.1:9999"
