apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "libvector.fullname" . }}
  labels:
    {{- include "libvector.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "libvector.selectorLabels" . | nindent 6 }}
  minReadySeconds: 1
  updateStrategy:
    type: {{ .Values.updateStrategy }}
  template:
    metadata:
      annotations:
        {{- include "libvector.rerollAnnotations" . | nindent 8 }}
        {{- include "libvector.metricsPrometheusPodAnnotations" . | nindent 8 }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "libvector.selectorLabels" . | nindent 8 }}
        vector.dev/exclude: "true"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "libvector.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.podPriorityClassName }}
      priorityClassName: {{ .Values.podPriorityClassName }}
      {{- end }}
      containers:
        - name: vector
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "libvector.image" . | quote }}
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          command:
            {{- toYaml .Values.command | nindent 12 }}
          args:
            - --config
            - /etc/vector/*.toml
          env:
            - name: VECTOR_SELF_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: VECTOR_SELF_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VECTOR_SELF_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if .Values.hostMetricsSource.enabled }}
            - name: PROCFS_ROOT
              value: /host/proc
            - name: SYSFS_ROOT
              value: /host/sys
            {{- end }}
            {{- include "libvector.globalEnv" . | nindent 12 }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            {{- include "libvector.metricsContainerPorts" . | nindent 12  }}
            {{- with .Values.extraContainersPorts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            # Host log directory mount.
            - name: var-log
              mountPath: /var/log/
              readOnly: true
            # Host mount for docker and containerd log file symlinks.
            - name: var-lib
              mountPath: /var/lib
              readOnly: true
            # Vector data dir mount.
            - name: data-dir
              mountPath: "{{ .Values.globalOptions.dataDir }}"
            # Vector config dir mount.
            - name: config-dir
              mountPath: /etc/vector
              readOnly: true
            {{- if .Values.hostMetricsSource.enabled }}
            # Host procsfs mount.
            - name: procfs
              mountPath: /host/proc
              readOnly: true
            # Host sysfs mount.
            - name: sysfs
              mountPath: /host/sys
              readOnly: true
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            # Extra volumes.
            {{- toYaml . | nindent 12 }}
            {{- end }}
      terminationGracePeriodSeconds: 60
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        # Log directory.
        - name: var-log
          hostPath:
            path: /var/log/
        # Docker and containerd log files in Kubernetes are symlinks to this folder.
        - name: var-lib
          hostPath:
            path: /var/lib/
        # Vector will store it's data here.
        - name: data-dir
          {{- toYaml .Values.dataVolume | nindent 10 }}
        # Vector config dir.
        - name: config-dir
          projected:
            sources:
              - configMap:
                  name: {{ include "libvector.configMapName" . }}
              {{- with .Values.extraConfigDirSources }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
        {{- if .Values.hostMetricsSource.enabled }}
        # Host procsfs.
        - name: procfs
          hostPath:
            path: /proc
        # Host sysfs.
        - name: sysfs
          hostPath:
            path: /sys
        {{- end }}
        {{- with .Values.extraVolumes }}
        # Extra volumes.
        {{- toYaml . | nindent 8 }}
        {{- end }}
