[[domains]]
name = "buffers"

[[domains]]
name = "cli"

[[domains]]
name = "config"

[[domains]]
name = "dependencies"

[[domains]]
name = "networking"

[[domains]]
name = "observability"

[[domains]]
name = "operations"

[[domains]]
name = "platforms"

[[domains]]
name = "privacy"

[[domains]]
name = "security"

[[domains]]
name = "sinks"

[[domains]]
name = "sources"

[[domains]]
name = "tests"

[[domains]]
name = "topology"

[[domains]]
name = "transforms"

[[domains]]
name = "ux"

[[domains]]
name = "website"
