[[installation.containers]]
id = "docker"
name = "Docker"
archs = ["x86_64", "ARM64", "ARMv7"]
oss = ["Linux", "MacOS"]


[[installation.operating_systems]]
id = "amazon-linux"
name = "Amazon Linux"
package_manager = "RPM"
os = "Linux"

[[installation.operating_systems]]
id = "centos"
name = "CentOS"
package_manager = "RPM"
os = "Linux"

[[installation.operating_systems]]
id = "debian"
name = "Debian"
package_manager = "DPKG"
os = "Linux"

[[installation.operating_systems]]
id = "macos"
name = "MacOS"
package_manager = "Homebrew"
os = "Linux"

[[installation.operating_systems]]
id = "Raspbian"
name = "Raspbian"
package_manager = "DPKG"
os = "Linux"

[[installation.operating_systems]]
id = "rhel"
name = "RHEL"
package_manager = "RPM"
os = "Linux"

[[installation.operating_systems]]
id = "ubuntu"
name = "Ubuntu"
package_manager = "DPKG"
os = "Linux"

[[installation.operating_systems]]
id = "windows"
name = "Windows"
os = "Windows"


[[installation.package_managers]]
id = "dpkg"
name = "DPKG"
archs = ["x86_64", "ARM64", "ARMv7"]

[[installation.package_managers]]
id = "homebrew"
name = "Homebrew"
archs = ["x86_64"]

[[installation.package_managers]]
id = "rpm"
name = "RPM"
archs = ["x86_64"]


[[installation.downloads]]
available_on_latest = true
available_on_nightly = true
arch = "x86_64"
file_name = "vector-x86_64-unknown-linux-musl.tar.gz"
file_type = "tar.gz"
name = "Linux (x86_64)"
os = "Linux"
type = "archive"

[[installation.downloads]]
available_on_latest = true
available_on_nightly = true
arch = "ARM64"
file_name = "vector-aarch64-unknown-linux-musl.tar.gz"
file_type = "tar.gz"
name = "Linux (ARM64)"
os = "Linux"
type = "archive"

[[installation.downloads]]
available_on_latest = true
available_on_nightly = true
arch = "ARMv7"
file_name = "vector-armv7-unknown-linux-musleabihf.tar.gz"
file_type = "tar.gz"
name = "Linux (ARMv7)"
os = "Linux"
type = "archive"

[[installation.downloads]]
available_on_latest = true
available_on_nightly = true
arch = "x86_64"
file_name = "vector-x86_64-apple-darwin.tar.gz"
file_type = "tar.gz"
name = "MacOS (x86_64)"
os = "MacOS"
type = "archive"

[[installation.downloads]]
available_on_latest = true
available_on_nightly = true
arch = "x86_64"
file_name = "vector-x86_64-pc-windows-msvc.zip"
file_type = "zip"
name = "Windows (x86_64, 7+)"
os = "Windows"
type = "archive"

[[installation.downloads]]
available_on_latest = true
available_on_nightly = true
arch = "x86_64"
file_name = "vector-amd64.deb"
file_type = "deb"
name = "Deb (x86_64)"
os = "Linux"
package_manager = "DPKG"
type = "package"

[[installation.downloads]]
available_on_latest = true
available_on_nightly = true
arch = "ARM64"
file_name = "vector-arm64.deb"
file_type = "deb"
name = "Deb (ARM64)"
os = "Linux"
package_manager = "DPKG"
type = "package"

[[installation.downloads]]
available_on_latest = true
available_on_nightly = true
arch = "ARMv7"
file_name = "vector-armhf.deb"
file_type = "deb"
name = "Deb (ARMv7)"
os = "Linux"
package_manager = "DPKG"
type = "package"

[[installation.downloads]]
available_on_latest = true
available_on_nightly = true
arch = "x86_64"
file_name = "vector-x86_64.rpm"
file_type = "rpm"
name = "RPM (x86_64)"
os = "Linux"
package_manager = "RPM"
type = "package"