[installation]
containers = [
  {name = "Docker", id = "docker"}
]
operating_systems = [
  {name = "Amazon Linux", id = "amazon-linux"},
  {name = "CentOS", id = "centos"},
  {name = "Debian", id = "debian"},
  {name = "MacOS", id = "macos"},
  {name = "Raspberry Pi", id = "raspberry-pi"},
  {name = "RHEL", id = "rhel"},
  {name = "Ubuntu", id = "ubuntu"},
  {name = "Windows", id = "windows"}
]
package_managers = [
  {name = "DPKG", id = "dpkg"},
  {name = "Homebrew", id = "homebrew"},
  {name = "RPM", id = "rpm"},
]

[[installation.downloads]]
cpu = "x86_64"
file_name = "vector-x86_64-unknown-linux-musl.tar.gz"
latest = true
name = "Linux (x86_64)"
nightly = true
os = "Linux"
type = "archive"

[[installation.downloads]]
cpu = "ARM64"
file_name = "vector-aarch64-unknown-linux-musl.tar.gz"
latest = false
name = "Linux (ARM64)"
nightly = true
os = "Linux"
type = "archive"

[[installation.downloads]]
cpu = "vector-armv7-unknown-linux-musleabihf"
file_name = "vector-armv7-unknown-linux-musleabihf.tar.gz"
latest = false
name = "Linux (ARMv7)"
nightly = true
os = "Linux"
type = "archive"

[[installation.downloads]]
cpu = "x86_64"
file_name = "vector-x86_64-apple-darwin.tar.gz"
latest = true
name = "MacOS (x86_64, 10.7+)"
nightly = true
os = "MacOS"
type = "archive"

[[installation.downloads]]
cpu = "x86_64"
file_name = "vector-x86_64-pc-windows-msvc.zip"
latest = false
name = "Windows (x86_64, 7+)"
nightly = true
os = "Windows"
type = "archive"

[[installation.downloads]]
cpu = "x86_64"
file_name = "vector-amd64.deb"
latest = true
name = "Deb (x86_64)"
nightly = true
os = "Linux"
type = "package"

[[installation.downloads]]
cpu = "aarch64"
file_name = "vector-arm64.deb"
latest = false
name = "Deb (ARM64)"
nightly = true
os = "Linux"
type = "package"

[[installation.downloads]]
cpu = "armv7"
file_name = "vector-armhf.deb"
latest = false
name = "Deb (ARMv7)"
nightly = true
os = "Linux"
type = "package"

[[installation.downloads]]
cpu = "x86_64"
file_name = "vector-x86_64.rpm"
latest = true
name = "RPM (x86_64)"
nightly = true
os = "Linux"
type = "package"