[links]

[links.docs]
agent_role = "/setup/deployment/roles/agent.md"
at_least_once_delivery = "/about/guarantees.md#at-least-once-delivery"
best_effort_delivery = "/about/guarantees.md#best-effort-delivery"
config_composition = "/usage/configuration/README.md#composition"
config_value_types = "/usage/configuration/README.md#value-types"
data_directory = "/usage/configuration/README.md#data-directory"
default_schema = "/about/data-model/log.md#default-schema"
download = "/setup/installation/manual/from-archives#1-download-the-archive"
event = "/about/data-model/README.md#event"
event_key_special_characters = "/about/data-model/log.md#special-characters"
from_source = "/setup/installation/manual/from-source.md"
log_event = "/about/data-model/log.md"
metric_event = "/about/data-model/metric.md"
metrics = "/usage/administration/monitoring.md#metrics"
monitoring_logs = "/usage/administration/monitoring.md#logs"
pipelines = "/usage/configuration/README.md#composition"
service_role = "/setup/deployment/roles/service.md"

[links.url]
add_company = "https://github.com/timberio/vector/blob/master/.meta/companies.toml"
apt = "https://wiki.debian.org/Apt"
aws_athena = "https://aws.amazon.com/athena/"
aws_athena_console = "https://console.aws.amazon.com/athena/home"
aws_access_keys = "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html"
aws_cloudwatch_logs_sink_source = "https://github.com/timberio/vector/blob/master/src/sinks/aws_cloudwatch_logs/mod.rs"
aws_elb = "https://aws.amazon.com/elasticloadbalancing/"
aws_credentials_file = "https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html"
aws_credential_process = "https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html"
aws_cw_logs = "https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/WhatIsCloudWatchLogs.html"
aws_cw_logs_group_name = "https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/Working-with-log-groups-and-streams.html"
aws_cw_logs_regions = "https://docs.aws.amazon.com/general/latest/gr/rande.html#cw_region"
aws_cw_logs_service_limits = "https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html"
aws_cw_logs_stream_name = "https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/Working-with-log-groups-and-streams.html"
aws_kinesis_data_streams = "https://aws.amazon.com/kinesis/data-streams/"
aws_kinesis_partition_key = "https://docs.aws.amazon.com/kinesis/latest/APIReference/API_PutRecordsRequestEntry.html#Streams-Type-PutRecordsRequestEntry-PartitionKey"
aws_kinesis_service_limits = "https://docs.aws.amazon.com/streams/latest/dev/service-sizes-and-limits.html"
aws_kinesis_split_shards = "https://docs.aws.amazon.com/streams/latest/dev/kinesis-using-sdk-java-resharding-split.html"
aws_s3 = "https://aws.amazon.com/s3/"
aws_s3_regions = "https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region"
aws_s3_service_limits = "https://docs.aws.amazon.com/streams/latest/dev/service-sizes-and-limits.html"
basic_auth = "https://en.wikipedia.org/wiki/Basic_access_authentication"
big_query_streaming = "https://cloud.google.com/bigquery/streaming-data-into-bigquery"
cgroups_limit_resources = "https://the.binbashtheory.com/control-resources-cgroups/"
clickhouse = "https://clickhouse.yandex/"
clickhouse_http = "https://clickhouse.yandex/docs/en/interfaces/http/"
community = "https://vector.dev/community"
configuration = "https://docs.vector.dev/usage/configuration"
crc = "https://en.wikipedia.org/wiki/Cyclic_redundancy_check"
default_configuration = "https://github.com/timberio/vector/blob/master/config/vector.toml"
docker = "https://www.docker.com/"
docker_alpine = "https://hub.docker.com/_/alpine"
dockerfile = "https://github.com/timberio/vector/blob/master/Dockerfile"
docker_hub_vector = "https://hub.docker.com/r/timberio/vector"
docs = "https://docs.vector.dev"
elasticsearch = "https://www.elastic.co/products/elasticsearch"
event_proto = "https://github.com/timberio/vector/blob/master/proto/event.proto"
exit_codes = "https://docs.rs/exitcode/1.1.2/exitcode/#constants"
file_sink_source = "https://github.com/timberio/vector/blob/master/src/sinks/file/mod.rs"
globbing = "https://en.wikipedia.org/wiki/Glob_(programming)"
grok = "http://grokdebug.herokuapp.com/"
grok_debugger = "http://grokdebug.herokuapp.com/"
grok_patterns = "https://github.com/daschl/grok/tree/master/patterns"
gzip = "https://www.gzip.org/"
haproxy = "https://www.haproxy.org/"
homebrew = "https://brew.sh/"
homebrew_services = "https://github.com/Homebrew/homebrew-services"
iam_instance_profile = "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2_instance-profiles.html"
initd = "https://bash.cyberciti.biz/guide//etc/init.d"
journald = "https://www.freedesktop.org/software/systemd/man/systemd-journald.service.html"
json_types = "https://en.wikipedia.org/wiki/JSON#Data_types_and_syntax"
kafka = "https://kafka.apache.org/"
kafka_partitioning_docs = "https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-Partitioningandbootstrapping"
kafka_protocol = "https://kafka.apache.org/protocol"
kubernetes_limit_resources = "https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/"
leveldb = "https://github.com/google/leveldb"
log_event_source = "https://github.com/timberio/vector/blob/master/src/event/mod.rs"
lua = "https://www.lua.org/"
lua_docs = "https://www.lua.org/manual/5.3/"
lua_manual = "http://www.lua.org/manual/5.1/manual.html"
lua_require = "http://www.lua.org/manual/5.1/manual.html#pdf-require"
lua_table = "https://www.lua.org/manual/2.2/section3_3.html"
lua_types = "https://www.lua.org/manual/2.2/section3_3.html"
mailing_list = "https://vector.dev/mailing_list/"
metric_event_source = "https://github.com/timberio/vector/blob/master/src/event/metric.rs"
musl_builder_docker_image = "https://github.com/timberio/vector/blob/master/scripts/ci-docker-images/builder-x86_64-unknown-linux-musl/Dockerfile"
new_bug_report = "https://github.com/timberio/vector/issues/new?labels=Type%3A+Bug"
new_feature_request = "https://github.com/timberio/vector/issues/new?labels=Type%3A+New+Feature"
new_sink = "https://github.com/timberio/vector/issues/new?labels=Type%3A+New+Feature"
new_source = "https://github.com/timberio/vector/issues/new?labels=Type%3A+New+Feature"
new_transform = "https://github.com/timberio/vector/issues/new?labels=Type%3A+New+Feature"
nginx = "https://www.nginx.com/"
prometheus = "https://prometheus.io/"
prometheus_counter = "https://prometheus.io/docs/concepts/metric_types/#counter"
prometheus_gauge = "https://prometheus.io/docs/concepts/metric_types/#gauge"
prometheus_high_cardinality = "https://prometheus.io/docs/practices/naming/#labels"
prometheus_histogram = "https://prometheus.io/docs/concepts/metric_types/#histogram"
prometheus_histograms_guide = "https://prometheus.io/docs/practices/histograms/"
prometheus_summary = "https://prometheus.io/docs/concepts/metric_types/#summary"
prometheus_text_based_exposition_format = "https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exposition_formats.md#text-based-format"
prometheus_metric_naming = "https://prometheus.io/docs/practices/naming/#metric-names"
rdkafka = "https://github.com/edenhill/librdkafka"
regex = "https://en.wikipedia.org/wiki/Regular_expression"
regex_grouping_and_flags = "https://docs.rs/regex/1.1.7/regex/#grouping-and-flags"
regex_tester = "https://regex-golang.appspot.com/assets/html/index.html"
releases = "https://github.com/timberio/vector/releases"
roadmap = "https://github.com/timberio/vector/milestones?direction=asc&sort=due_date&state=open"
rust = "https://www.rust-lang.org/"
rust_date_time = "https://docs.rs/chrono/0.4.0/chrono/struct.DateTime.html"
rust_grok_library = "https://github.com/daschl/grok"
rust_regex_syntax = "https://docs.rs/regex/1.1.7/regex/#syntax"
rust_target_triples  = "https://forge.rust-lang.org/platform-support.html"
splunk_hec = "http://dev.splunk.com/view/event-collector/SP-CAAAE6M"
splunk_hec_setup = "https://docs.splunk.com/Documentation/Splunk/latest/Data/UsetheHTTPEventCollector"
standard_streams = "https://en.wikipedia.org/wiki/Standard_streams"
statsd_set = "https://github.com/statsd/statsd/blob/master/docs/metric_types.md#sets"
strftime_specifiers = "https://docs.rs/chrono/0.3.1/chrono/format/strftime/index.html"
syslog_5424 = "https://tools.ietf.org/html/rfc5424"
systemd = "https://www.freedesktop.org/wiki/Software/systemd/"
systemd_limit_resources = "https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html"
test_harness = "https://github.com/timberio/vector-test-harness/"
toml = "https://github.com/toml-lang/toml"
toml_array = "https://github.com/toml-lang/toml#array"
toml_table = "https://github.com/toml-lang/toml#table"
toml_types = "https://github.com/toml-lang/toml#table-of-contents"
uuidv4 = "https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_(random)"
vector_repo = "https://github.com/timberio/vector"
vector_initd_service = "https://github.com/timberio/vector/blob/master/distribution/init.d/vector"
vector_systemd_file = "https://github.com/timberio/vector/blob/master/distribution/systemd/vector.service"
vote_feature = "https://github.com/timberio/vector/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc+label%3A%22Type%3A+New+Feature%22"
vector_chat = "https://chat.vector.dev"
website = "https://vector.dev"
yum = "http://yum.baseurl.org/"
