[links]

[links.pages]
aws_components = "/components?providers%5B%5D=aws"

[links.urls]
add_company = "https://github.com/timberio/vector/blob/master/.meta/companies.toml"
arm = "https://en.wikipedia.org/wiki/ARM_architecture"
aws_arm_g2_announcement = "https://aws.amazon.com/about-aws/whats-new/2019/12/announcing-new-amazon-ec2-m6g-c6g-and-r6g-instances-powered-by-next-generation-arm-based-aws-graviton2-processors/"
aws_athena = "https://aws.amazon.com/athena/"
aws_athena_console = "https://console.aws.amazon.com/athena/home"
aws_access_keys = "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html"
aws_cloudwatch_logs_sink_source = "https://github.com/timberio/vector/blob/master/src/sinks/aws_cloudwatch_logs/mod.rs"
aws_elb = "https://aws.amazon.com/elasticloadbalancing/"
aws_credentials_file = "https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html"
aws_credential_process = "https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html"
aws_cw_logs = "https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/WhatIsCloudWatchLogs.html"
aws_cw_logs_group_name = "https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/Working-with-log-groups-and-streams.html"
aws_cw_logs_service_limits = "https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html"
aws_cw_logs_stream_name = "https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/Working-with-log-groups-and-streams.html"
aws_cw_logs_regions = "https://docs.aws.amazon.com/general/latest/gr/rande.html#cwl_region"
aws_cw_metrics = "https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/working_with_metrics.html"
aws_cw_metrics_service_limits = "https://docs.aws.amazon.com/en_pv/AmazonCloudWatch/latest/monitoring/cloudwatch_limits.html"
aws_cw_metrics_regions = "https://docs.aws.amazon.com/general/latest/gr/rande.html#cw_region"
aws_elasticsearch = "https://aws.amazon.com/elasticsearch-service/"
aws_elasticsearch_regions = "https://docs.aws.amazon.com/general/latest/gr/rande.html#elasticsearch-service-regions"
aws_kinesis_data_streams = "https://aws.amazon.com/kinesis/data-streams/"
aws_kinesis_data_firehose = "https://aws.amazon.com/kinesis/data-firehose/"
aws_kinesis_partition_key = "https://docs.aws.amazon.com/kinesis/latest/APIReference/API_PutRecordsRequestEntry.html#Streams-Type-PutRecordsRequestEntry-PartitionKey"
aws_kinesis_streams_service_limits = "https://docs.aws.amazon.com/streams/latest/dev/service-sizes-and-limits.html"
aws_kinesis_firehose_service_limits = "https://docs.aws.amazon.com/firehose/latest/dev/limits.html"
aws_kinesis_split_shards = "https://docs.aws.amazon.com/streams/latest/dev/kinesis-using-sdk-java-resharding-split.html"
aws_s3 = "https://aws.amazon.com/s3/"
aws_s3_endpoints = "https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_endpoint"
aws_s3_regions = "https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region"
aws_s3_service_limits = "https://docs.aws.amazon.com/streams/latest/dev/service-sizes-and-limits.html"
basic_auth = "https://en.wikipedia.org/wiki/Basic_access_authentication"
big_query_streaming = "https://cloud.google.com/bigquery/streaming-data-into-bigquery"
cgroups_limit_resources = "https://the.binbashtheory.com/control-resources-cgroups/"
clickhouse = "https://clickhouse.yandex/"
clickhouse_http = "https://clickhouse.yandex/docs/en/interfaces/http/"
conventional_commits = "https://www.conventionalcommits.org"
crc = "https://en.wikipedia.org/wiki/Cyclic_redundancy_check"
datadog = "https://www.datadoghq.com"
default_configuration = "https://github.com/timberio/vector/blob/master/config/vector.toml"
docker = "https://www.docker.com/"
docker_alpine = "https://hub.docker.com/_/alpine"
docker_debian = "https://hub.docker.com/_/debian"
dockerfile = "https://github.com/timberio/vector/blob/master/Dockerfile"
docker_hub_vector = "https://hub.docker.com/r/timberio/vector"
docker_daemon = "https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-socket-option"
docker_object_labels = "https://docs.docker.com/config/labels-custom-metadata/"
docs = "https://vector.dev/docs/"
dpkg = "https://wiki.debian.org/dpkg"
elasticsearch = "https://www.elastic.co/products/elasticsearch"
event_proto = "https://github.com/timberio/vector/blob/master/proto/event.proto"
exit_codes = "https://docs.rs/exitcode/1.1.2/exitcode/#constants"
file_sink_source = "https://github.com/timberio/vector/blob/master/src/sinks/file/mod.rs"
gcp_pubsub = "https://cloud.google.com/pubsub/"
gcp_pubsub_rest = "https://cloud.google.com/pubsub/docs/reference/rest/"
globbing = "https://en.wikipedia.org/wiki/Glob_(programming)"
grok = "http://grokdebug.herokuapp.com/"
grok_debugger = "http://grokdebug.herokuapp.com/"
grok_patterns = "https://github.com/daschl/grok/tree/master/patterns"
gzip = "https://www.gzip.org/"
haproxy = "https://www.haproxy.org/"
homebrew = "https://brew.sh/"
homebrew_services = "https://github.com/Homebrew/homebrew-services"
iam_instance_profile = "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2_instance-profiles.html"
iana_time_zone_format = "https://en.wikipedia.org/wiki/Tz_database#Names_of_time_zones"
iana_time_zones = "https://en.wikipedia.org/wiki/List_of_tz_database_time_zones"
initd = "https://bash.cyberciti.biz/guide//etc/init.d"
inode = "https://en.wikipedia.org/wiki/Inode"
iso3166-2 = "https://en.wikipedia.org/wiki/ISO_3166-2"
jemalloc = "https://github.com/jemalloc/jemalloc"
journald = "https://www.freedesktop.org/software/systemd/man/systemd-journald.service.html"
json_types = "https://en.wikipedia.org/wiki/JSON#Data_types_and_syntax"
kafka = "https://kafka.apache.org/"
kafka_partitioning_docs = "https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-Partitioningandbootstrapping"
kafka_protocol = "https://kafka.apache.org/protocol"
kubernetes_limit_resources = "https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/"
kubernetes_daemonset = "https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/"
kubernetes_example_daemonset = "https://github.com/timberio/vector/blob/master/config/kubernetes/vector-daemonset.yaml"
leveldb = "https://github.com/google/leveldb"
leveldb-sys-2 = "https://crates.io/crates/leveldb-sys"
leveldb-sys-3 = "https://github.com/timberio/leveldb-sys/tree/v3.0.0"
lib_rdkafka = "https://github.com/edenhill/librdkafka"
lib_rdkafka_config = "https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md"
log_event_source = "https://github.com/timberio/vector/blob/master/src/event/mod.rs"
lua = "https://www.lua.org/"
lua_docs = "https://www.lua.org/manual/5.3/"
lua_manual = "http://www.lua.org/manual/5.1/manual.html"
lua_require = "http://www.lua.org/manual/5.1/manual.html#pdf-require"
lua_table = "https://www.lua.org/manual/2.2/section3_3.html"
lua_types = "https://www.lua.org/manual/2.2/section3_3.html"
mailing_list = "https://vector.dev/community/"
metric_event_source = "https://github.com/timberio/vector/blob/master/src/event/metric.rs"
musl_builder_docker_image = "https://github.com/timberio/vector/blob/master/scripts/ci-docker-images/builder-x86_64-unknown-linux-musl/Dockerfile"
new_bug_report = "https://github.com/timberio/vector/issues/new?labels=type%3A+bug"
new_feature_request = "https://github.com/timberio/vector/issues/new?labels=type%3A+new+feature"
new_relic = "https://newrelic.com/"
new_relic_log_api = "https://docs.newrelic.com/docs/logs/new-relic-logs/log-api/introduction-log-api"
new_security_report = "https://github.com/timberio/vector/issues/new?labels=domain%3A+security"
new_sink = "https://github.com/timberio/vector/issues/new?labels=type%3A+new+feature"
new_source = "https://github.com/timberio/vector/issues/new?labels=type%3A+new+feature"
new_target = "https://github.com/timberio/vector/issues/new?labels=type%3A+task&labels=domain%3A+operations"
new_transform = "https://github.com/timberio/vector/issues/new?labels=type%3A+new+feature"
nginx = "https://www.nginx.com/"
openssl = "https://www.openssl.org/"
perl_windows = "https://www.perl.org/get.html#win32"
prometheus = "https://prometheus.io/"
prometheus_counter = "https://prometheus.io/docs/concepts/metric_types/#counter"
prometheus_gauge = "https://prometheus.io/docs/concepts/metric_types/#gauge"
prometheus_high_cardinality = "https://prometheus.io/docs/practices/naming/#labels"
prometheus_histogram = "https://prometheus.io/docs/concepts/metric_types/#histogram"
prometheus_histograms_guide = "https://prometheus.io/docs/practices/histograms/"
prometheus_summary = "https://prometheus.io/docs/concepts/metric_types/#summary"
prometheus_text_based_exposition_format = "https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exposition_formats.md#text-based-format"
prometheus_metric_naming = "https://prometheus.io/docs/practices/naming/#metric-names"
rdkafka = "https://github.com/edenhill/librdkafka"
regex = "https://en.wikipedia.org/wiki/Regular_expression"
regex_grouping_and_flags = "https://docs.rs/regex/1.1.7/regex/#grouping-and-flags"
regex_tester = "https://rustexp.lpil.uk/"
rpm = "https://rpm.org/"
rust = "https://www.rust-lang.org/"
rust_date_time = "https://docs.rs/chrono/0.4.0/chrono/struct.DateTime.html"
rust_grok_library = "https://github.com/daschl/grok"
rust_regex_syntax = "https://docs.rs/regex/1.1.7/regex/#syntax"
rust_target_triples  = "https://forge.rust-lang.org/platform-support.html"
rust_tier_1_platform = "https://forge.rust-lang.org/release/platform-support.html#tier-1"
rustup = "https://rustup.rs"
splunk_hec = "http://dev.splunk.com/view/event-collector/SP-CAAAE6M"
splunk_hec_event_endpoint = "https://docs.splunk.com/Documentation/Splunk/8.0.0/RESTREF/RESTinput#services.2Fcollector.2Fevent"
splunk_hec_indexed_fields = "https://docs.splunk.com/Documentation/Splunk/8.0.0/Data/IFXandHEC"
splunk_hec_protocol = "https://docs.splunk.com/Documentation/Splunk/8.0.0/Data/HECRESTendpoints"
splunk_hec_raw_endpoint = "https://docs.splunk.com/Documentation/Splunk/8.0.0/RESTREF/RESTinput#services.2Fcollector.2Fraw"
splunk_hec_setup = "https://docs.splunk.com/Documentation/Splunk/latest/Data/UsetheHTTPEventCollector"
standard_streams = "https://en.wikipedia.org/wiki/Standard_streams"
statsd = "https://github.com/statsd/statsd"
statsd_multi = "https://github.com/statsd/statsd/blob/master/docs/metric_types.md#multi-metric-packets"
statsd_set = "https://github.com/statsd/statsd/blob/master/docs/metric_types.md#sets"
stderr = "https://en.wikipedia.org/wiki/Standard_streams#Standard_error_(stderr)"
stdout = "https://en.wikipedia.org/wiki/Standard_streams#Standard_output_(stdout)"
strptime_specifiers = "https://docs.rs/chrono/0.3.1/chrono/format/strftime/index.html"
syslog_3164 = "https://tools.ietf.org/html/rfc3164"
syslog_5424 = "https://tools.ietf.org/html/rfc5424"
systemd = "https://www.freedesktop.org/wiki/Software/systemd/"
systemd_limit_resources = "https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html"
test_harness = "https://github.com/timberio/vector-test-harness/"
toml = "https://github.com/toml-lang/toml"
toml_array = "https://github.com/toml-lang/toml#array"
toml_table = "https://github.com/toml-lang/toml#table"
toml_types = "https://github.com/toml-lang/toml#table-of-contents"
uuidv4 = "https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_(random)"
vector_blog = "https://vector.dev/blog"
vector_bug_issues = "https://github.com/timberio/vector/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22"
vector_changelog = "https://github.com/timberio/vector/blob/master/CHANGELOG.md"
vector_chat = "https://chat.vector.dev"
vector_community = "https://vector.dev/community"
vector_docker_source_files = "https://github.com/timberio/vector/tree/master/distribution/docker"
vector_download = "https://vector.dev/releases/latest/download"
vector_initd_service = "https://github.com/timberio/vector/blob/master/distribution/init.d/vector"
vector_issues = "https://github.com/timberio/vector/issues"
vector_nightly_builds = "http://packages.timber.io/vector/nightly/latest/"
vector_releases = "https://vector.dev/releases/latest"
vector_repo = "https://github.com/timberio/vector"
vector_roadmap = "https://github.com/timberio/vector/milestones?direction=asc&sort=due_date&state=open"
vector_systemd_file = "https://github.com/timberio/vector/blob/master/distribution/systemd/vector.service"
vector_twitter = "https://twitter.com/timberdotio"
vector_version_branches = "https://github.com/timberio/vector/branches/all?query=v"
vote_feature = "https://github.com/timberio/vector/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc+label%3A%22Type%3A+New+Feature%22"
website = "https://vector.dev"
windows_service = "https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-service"
zlib = "https://www.zlib.net"
