[options.data_dir]
type = "string"
examples = ["/var/lib/vector"]
description = """\
The directory used for persisting Vector state, such as on-disk buffers, \
file checkpoints, and more. Please make sure the Vector project has write \
permissions to this dir.\
"""

[options.dns_servers]
type = "[string]"
examples = [["0.0.0.0:53"]]
description = """\
The list of DNS servers Vector will use to resolve DNS requests. When set \
Vector will ignore the system configuration and use only the list of DNS \
servers provided. If this option is not set then Vector will attempt to use \
the system configuration.\
"""
