version: "2"

services:
  datadog-agent:
    image: datadog/agent:7
    # we need to enable the network mode considering datadog-agent needs to
    # communicate with vector running on the host.
    network_mode: host
    environment:
      - DD_API_KEY
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_LOGS_DD_URL=0.0.0.0:8080
      - DD_LOGS_CONFIG_LOGS_NO_SSL=true
      - DD_LOGS_CONFIG_USE_HTTP=true
      - DD_LOGS_CONFIG_USE_V2_API=false
    volumes:
      - ${PWD}/tests/data/datadog-agent/conf.yaml:/etc/datadog-agent/conf.d/test.d/conf.yaml

