version: "3"

services:
  nats:
    image: docker.io/library/nats:latest
    networks:
      - backend
  nats-userpass:
    image: docker.io/library/nats:latest
    command: ["--user", "natsuser", "--pass", "natspass"]
    networks:
      - backend
  nats-token:
    image: docker.io/library/nats:latest
    command: ["--auth", "secret"]
    networks:
      - backend
  nats-nkey:
    image: docker.io/library/nats:latest
    command: ["--config", "/usr/share/nats/config/nats-nkey.conf"]
    networks:
      - backend
    volumes:
      - ${PWD}/tests/data/nats:/usr/share/nats/config
  nats-tls:
    image: docker.io/library/nats:latest
    command: ["--config", "/usr/share/nats/config/nats-tls.conf"]
    networks:
      - backend
    volumes:
      - ${PWD}/tests/data/nats:/usr/share/nats/config
  nats-tls-client-cert:
    image: docker.io/library/nats:latest
    command: ["--config", "/usr/share/nats/config/nats-tls-client-cert.conf"]
    networks:
      - backend
    volumes:
      - ${PWD}/tests/data/nats:/usr/share/nats/config
  nats-jwt:
    image: docker.io/library/nats:latest
    command: ["--config", "/usr/share/nats/config/nats-jwt.conf"]
    networks:
      - backend
    volumes:
      - ${PWD}/tests/data/nats:/usr/share/nats/config
  runner:
    build:
      context: ${PWD}
      dockerfile: scripts/integration/Dockerfile
      args:
        - RUST_VERSION=${RUST_VERSION}
    working_dir: /code
    command:
      - "cargo"
      - "nextest"
      - "run"
      - "--retries"
      - "0"
      - "--no-fail-fast"
      - "--no-default-features"
      - "--features"
      - "nats-integration-tests"
      - "--lib"
      - "::nats::"
      - "--"
      - "--nocapture"
    depends_on:
      - nats
      - nats-userpass
      - nats-token
      - nats-nkey
      - nats-tls
      - nats-tls-client-cert
      - nats-jwt
    environment:
      - NATS_ADDRESS=nats://nats:4222
      - NATS_USERPASS_ADDRESS=nats://nats-userpass:4222
      - NATS_TOKEN_ADDRESS=nats://nats-token:4222
      - NATS_NKEY_ADDRESS=nats://nats-nkey:4222
      - NATS_TLS_ADDRESS=nats://nats-tls:4222
      - NATS_TLS_CLIENT_CERT_ADDRESS=nats://nats-tls-client-cert:4222
      - NATS_JWT_ADDRESS=nats://nats-jwt:4222
    networks:
      - backend
    volumes:
      - ${PWD}:/code
      - target:/code/target
      - cargogit:/usr/local/cargo/git
      - cargoregistry:/usr/local/cargo/registry

networks:
  backend: {}

volumes:
  target: {}
  cargogit: {}
  cargoregistry: {}
