services:
  local-azure-blob:
    image: mcr.microsoft.com/azure-storage/azurite:3.11.0
    command: azurite --blobHost 0.0.0.0 --loose
    volumes:
      - /var/run:/var/run

  runner:
    build:
      context: ${PWD}
      dockerfile: scripts/integration/Dockerfile
      args:
        - RUST_VERSION=${RUST_VERSION}
    working_dir: /code
    command:
      - "cargo"
      - "test"
      - "--no-fail-fast"
      - "--no-default-features"
      - "--features"
      - "azure-integration-tests"
      - "--lib"
      - "::azure_"
      - "--"
      - "--nocapture"
    environment:
      - AZURE_ADDRESS=local-azure-blob
      - HEARTBEAT_ADDRESS=0.0.0.0:8080
      - LOGSTASH_ADDRESS=0.0.0.0:8081
    depends_on:
      - local-azure-blob
    volumes:
      - ${PWD}:/code
      - cargogit:/usr/local/cargo/git
      - cargoregistry:/usr/local/cargo/registry

# this is made to improve the build when running locally
volumes:
  cargogit: {}
  cargoregistry: {}

