services:
  influxdb:
    image: influxdb:${INFLUXDB_VERSION:-1.8}
    network_mode: host
    environment:
      - INFLUXDB_REPORTING_DISABLED=true

  influxdb-tls:
    image: influxdb:${INFLUXDB_VERSION:-1.8}
    network_mode: host
    environment:
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_HTTP_HTTPS_ENABLED=true
      - INFLUXDB_HTTP_BIND_ADDRESS=:8087
      - INFLUXDB_BIND_ADDRESS=:8089
      - INFLUXDB_HTTP_HTTPS_CERTIFICATE=/etc/ssl/localhost.crt
      - INFLUXDB_HTTP_HTTPS_PRIVATE_KEY=/etc/ssl/localhost.key
    volumes:
      - ${PWD}/tests/data:/etc/ssl:ro

  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-v2.33.4}
    command: --config.file=/etc/vector/prometheus.yaml
    network_mode: host
    volumes:
      - ${PWD}/tests/data:/etc/vector:ro

  runner:
    build:
      context: ${PWD}
      dockerfile: scripts/integration/Dockerfile
      args:
        - RUST_VERSION=${RUST_VERSION}
    working_dir: /code
    network_mode: host
    command:
      - "cargo"
      - "nextest"
      - "run"
      - "--no-fail-fast"
      - "--no-default-features"
      - "--features"
      - "prometheus-integration-tests"
      - "--lib"
      - "${FILTER:-::prometheus::}"
      - "--"
      - "--nocapture"
    depends_on:
      - influxdb
      - influxdb-tls
      - prometheus
    volumes:
      - cargogit:/usr/local/cargo/git
      - cargoregistry:/usr/local/cargo/registry
      - ${PWD}:/code

# this is made to improve the build when running locally
volumes:
  cargogit: {}
  cargoregistry: {}
