services:
  splunk-hec:
    image: splunk/splunk:${SPLUNK_VERSION:-8.2.4}
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=password
      - SPLUNK_HEC_TOKEN=abcd1234
    volumes:
      - ${PWD}/tests/data/splunk/default.yml:/tmp/defaults/default.yml
    ports:
      - 8000:8000
      - 8088:8088
      - 8089:8089

  runner:
    build:
      context: ${PWD}
      dockerfile: scripts/integration/Dockerfile
      args:
        - RUST_VERSION=${RUST_VERSION}
    working_dir: /code
    command:
      - "cargo"
      - "test"
      - "--no-fail-fast"
      - "--no-default-features"
      - "--features"
      - "splunk-integration-tests"
      - "--lib"
      - "${FILTER:-::splunk_hec::}"
      - "--"
      - "--nocapture"
    depends_on:
      - splunk-hec
    environment:
      - SPLUNK_HEC_ADDRESS=http://splunk-hec:8088
      - SPLUNK_API_ADDRESS=https://splunk-hec:8089
    volumes:
      - cargogit:/usr/local/cargo/git
      - cargoregistry:/usr/local/cargo/registry
      - ${PWD}:/code

# this is made to improve the build when running locally
volumes:
  cargogit: {}
  cargoregistry: {}
