version: "3"

services:
  loki:
    image: docker.io/grafana/loki:${LOKI_VERSION:-2.4.1}
    command: -config.file=/etc/loki/local-config.yaml -auth.enabled=true
  runner:
    build:
      context: ${PWD}
      dockerfile: scripts/integration/Dockerfile
      args:
        - RUST_VERSION=${RUST_VERSION}
    working_dir: /code
    command:
      - "cargo"
      - "nextest"
      - "run"
      - "--no-fail-fast"
      - "--no-default-features"
      - "--features"
      - "loki-integration-tests"
      - "--lib"
      - "::loki::"
      - "--"
      - "--nocapture"
    depends_on:
      - loki
    environment:
      - LOKI_ADDRESS=http://loki:3100
    volumes:
      - ${PWD}:/code
      - target:/code/target
      - cargogit:/usr/local/cargo/git
      - cargoregistry:/usr/local/cargo/registry

networks:
  backend: {}

volumes:
  target: {}
  cargogit: {}
  cargoregistry: {}
