version: "2"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9091,SSL://:9092,SASL_PLAINTEXT://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9091,SSL://kafka:9092,SASL_PLAINTEXT://kafka:9093
      - KAFKA_SSL_KEYSTORE_LOCATION=/certs/kafka.p12
      - KAFKA_SSL_KEYSTORE_PASSWORD=NOPASS
      - KAFKA_SSL_TRUSTSTORE_LOCATION=/certs/kafka.p12
      - KAFKA_SSL_TRUSTSTORE_PASSWORD=NOPASS
      - KAFKA_SSL_KEY_PASSWORD=NOPASS
      - KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=none
      - "KAFKA_OPTS=-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      - KAFKA_INTER_BROKER_LISTENER_NAME=SASL_PLAINTEXT
      - KAFKA_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
    ports:
      - 9091:9091
      - 9092:9092
      - 9093:9093
    volumes:
      - ${PWD}/tests/data/kafka.p12:/certs/kafka.p12:ro
      - ${PWD}/tests/data/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf

  runner:
    build:
      context: ${PWD}
      dockerfile: scripts/integration/Dockerfile
      args:
        - RUST_VERSION=${RUST_VERSION}
    working_dir: /code
    command:
      - "cargo"
      - "nextest"
      - "run"
      - "--no-fail-fast"
      - "--no-default-features"
      - "--features"
      - "shutdown-tests"
      - "--test"
      - "shutdown"
      - "--"
      - "--test-threads"
      - "4"
      - "--nocapture"
    depends_on:
      - kafka
    environment:
      - KAFKA_HOST=kafka
    volumes:
      - cargogit:/usr/local/cargo/git
      - cargoregistry:/usr/local/cargo/registry
      - ${PWD}:/code
      - /var/run/docker.sock:/var/run/docker.sock:ro

# this is made to improve the build when running locally
volumes:
  cargogit: {}
  cargoregistry: {}

