version: "3"

services:
  beats-heartbeat:
    image: docker.elastic.co/beats/heartbeat:7.12.1
    networks:
      - backend
    # adding `-strict.perms=false to the default cmd as otherwise heartbeat was
    # complaining about the file permissions when running in CI
    # https://www.elastic.co/guide/en/beats/libbeat/5.3/config-file-permissions.html
    command: -environment=container -strict.perms=false
    volumes:
      - ${PWD}/tests/data/logstash/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro

  logstash:
    image: docker.elastic.co/logstash/logstash:7.13.1
    networks:
      - backend
    volumes:
      - /dev/null:/usr/share/logstash/pipeline/logstash.yml
      - ${PWD}/tests/data/host.docker.internal.crt:/tmp/logstash.crt
      - ${PWD}/tests/data/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf

  runner:
    build:
      context: ${PWD}
      dockerfile: scripts/integration/Dockerfile
      args:
        - RUST_VERSION=${RUST_VERSION}
    working_dir: /code
    hostname: runner
    networks:
      - backend
    command:
      - "cargo"
      - "nextest"
      - "run"
      - "--no-fail-fast"
      - "--no-default-features"
      - "--features"
      - "logstash-integration-tests"
      - "--lib"
      - "::logstash::integration_tests::"
    environment:
      - HEARTBEAT_ADDRESS=0.0.0.0:8080
      - LOGSTASH_ADDRESS=0.0.0.0:8081
    depends_on:
      - beats-heartbeat
      - logstash
    volumes:
      - ${PWD}:/code
      - target:/code/target
      - cargogit:/usr/local/cargo/git
      - cargoregistry:/usr/local/cargo/registry

networks:
  backend: {}

volumes:
  target: {}
  cargogit: {}
  cargoregistry: {}
