version: "2"

services:
  datadog-agent:
    image: datadog/agent:7
    network_mode: host
    environment:
      - DD_API_KEY=${TEST_DATADOG_API_KEY}
      - DD_APM_ENABLED=false
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_LOGS_DD_URL=0.0.0.0:8080
      - DD_LOGS_CONFIG_LOGS_NO_SSL=true
      - DD_LOGS_CONFIG_USE_HTTP=true
      - DD_HEALTH_PORT=8182
      - DD_CMD_PORT=5001
      - DD_USE_DOGSTATSD=false
    volumes:
      - ${PWD}/tests/data/datadog-agent/conf.yaml:/etc/datadog-agent/conf.d/test.d/conf.yaml

  datadog-trace-agent:
    # Using 7.31.0 image to have the ability mimic tracing lib using json
    image: datadog/agent:7.31.0
    network_mode: host
    environment:
      - DD_API_KEY=${TEST_DATADOG_API_KEY}
      - DD_APM_ENABLED=true
      - DD_APM_DD_URL=http://127.0.0.1:8081
      - DD_HEALTH_PORT=8183
      - DD_CMD_PORT=5002
      - DD_USE_DOGSTATSD=false

  runner:
    build:
      context: ${PWD}
      dockerfile: scripts/integration/Dockerfile
      args:
        - RUST_VERSION=${RUST_VERSION}
    working_dir: /code
    network_mode: host
    command:
      - "cargo"
      - "nextest"
      - "run"
      - "--no-fail-fast"
      - "--no-default-features"
      - "--features"
      - "datadog-agent-integration-tests"
      - "--lib"
      - "sources::datadog::agent::integration_tests::"
      - "--"
      - "--nocapture"
    depends_on:
      - datadog-agent
      - datadog-trace-agent
    volumes:
      - cargogit:/usr/local/cargo/git
      - cargoregistry:/usr/local/cargo/registry
      - ${PWD}:/code

# this is made to improve the build when running locally
volumes:
  cargogit: {}
  cargoregistry: {}

