version: "3"

services:
  runner:
    build:
      context: ${PWD}
      dockerfile: scripts/integration/Dockerfile
      args:
        - RUST_VERSION=${RUST_VERSION}
    working_dir: /code
    network_mode: host
    command:
      - "cargo"
      - "nextest"
      - "run"
      - "--no-fail-fast"
      - "--no-default-features"
      - "--features"
      - "fluent-integration-tests"
      - "--lib"
      - "::fluent::"
    volumes:
      - ${PWD}:/code
      - target:/code/target
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
      - cargogit:/usr/local/cargo/git
      - cargoregistry:/usr/local/cargo/registry

volumes:
  target: {}
  cargogit: {}
  cargoregistry: {}
