version: "3"

services:
  dnstap:
    build:
      context: ${PWD}/tests/data/dnstap
    container_name: vector_dnstap
    hostname: ns.example.com
    volumes:
      - dnstap-sockets:/bind1/etc/bind/socket
      - dnstap-sockets:/bind2/etc/bind/socket
      - dnstap-sockets:/bind3/etc/bind/socket
  runner:
    build:
      context: ${PWD}
      dockerfile: scripts/integration/Dockerfile
      args:
        - RUST_VERSION=${RUST_VERSION}
    working_dir: /code
    command:
      - "cargo"
      - "nextest"
      - "run"
      - "--no-fail-fast"
      - "--no-default-features"
      - "--features"
      - "dnstap-integration-tests"
      - "--lib"
      - "::dnstap::"
      - "--"
      - "--nocapture"
    depends_on:
      - dnstap
    environment:
      - BIND_SOCKET=/run/bind/socket
      - RUST_BACKTRACE=1
    volumes:
      - ${PWD}:/code
      - target:/code/target
      - /var/run/docker.sock:/var/run/docker.sock
      - cargogit:/usr/local/cargo/git
      - cargoregistry:/usr/local/cargo/registry
      - dnstap-sockets:/run/bind/socket

volumes:
  target: {}
  cargogit: {}
  cargoregistry: {}
  dnstap-sockets: {}
