version: "3"

services:
  # https://github.com/sigoden/dufs
  # serves static files at an HTTP endpoint
  dufs:
    image: docker.io/sigoden/dufs:latest
    networks:
      - backend
    command:
      - "/data"
    volumes:
      - ${PWD}/tests/data/http-scrape/serve:/data
  # To validate Basic HTTP authentication option
  dufs-auth:
    image: docker.io/sigoden/dufs:latest
    networks:
      - backend
    command:
      - "-a"
      - "/@user:pass"
      - "--auth-method"
      - "basic"
      - "/data"
    volumes:
      - ${PWD}/tests/data/http-scrape/serve:/data
  # To validate TLS options
  dufs-https:
    image: docker.io/sigoden/dufs:latest
    networks:
      - backend
    command:
      - "--tls-cert"
      - "/certs/ca.cert.pem"
      - "--tls-key"
      - "/certs/ca.key.pem"
      - "/data"
    volumes:
      - ${PWD}/tests/data/http-scrape/serve:/data
      - ${PWD}/tests/data/ca/intermediate_server/certs/dufs-https-chain.cert.pem:/certs/ca.cert.pem
      - ${PWD}/tests/data/ca/intermediate_server/private/dufs-https.key.pem:/certs/ca.key.pem
  runner:
    build:
      context: ${PWD}
      dockerfile: scripts/integration/Dockerfile
      args:
        - RUST_VERSION=${RUST_VERSION}
    working_dir: /code
    networks:
      - backend
    command:
      - "cargo"
      - "nextest"
      - "run"
      - "--no-fail-fast"
      - "--no-default-features"
      - "--features"
      - "http-scrape-integration-tests"
      - "--lib"
      - "sources::http_scrape::"
    depends_on:
      - dufs
      - dufs-auth
      - dufs-https
    environment:
      - DUFS_ADDRESS=http://dufs:5000
      - DUFS_AUTH_ADDRESS=http://dufs-auth:5000
      - DUFS_HTTPS_ADDRESS=https://dufs-https:5000
    volumes:
      - ${PWD}:/code
      - target:/code/target
      - cargogit:/usr/local/cargo/git
      - cargoregistry:/usr/local/cargo/registry

networks:
  backend: {}

volumes:
  target: {}
  cargogit: {}
  cargoregistry: {}
