version: "3"

services:
  redis:
    image: docker.io/redis:6-alpine
    networks:
      - backend
  runner:
    build:
      context: ${PWD}
      dockerfile: scripts/integration/Dockerfile
      args:
        - RUST_VERSION=${RUST_VERSION}
    working_dir: /code
    command:
      - "cargo"
      - "nextest"
      - "run"
      - "--no-fail-fast"
      - "--no-default-features"
      - "--features"
      - "redis-integration-tests"
      - "--lib"
      - "::redis::"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    networks:
      - backend
    volumes:
      - ${PWD}:/code
      - target:/code/target
      - cargogit:/usr/local/cargo/git
      - cargoregistry:/usr/local/cargo/registry

networks:
  backend: {}

volumes:
  target: {}
  cargogit: {}
  cargoregistry: {}
