[sources.docker]
title = "Docker"
beta = true
common = true
delivery_guarantee = "best_effort"
function_category = "collect"
guides = []
output_types = ["log"]
resources = []
through_description = "the docker engine daemon"

[sources.docker.env_vars.DOCKER_HOST]
type = "string"
default = "unix:///var/run/docker.sock"
examples = ["unix://path/to/socket", "tcp://host:2375/path"]
null = false
optional = true
description = "The docker host to connect to."

[sources.docker.env_vars.DOCKER_VERIFY_TLS]
type = "bool"
default = true
null = false
optional = true
description = """\
If `true` (the default), Vector will validate the TLS certificate of the \
remote host. Do NOT set this to `false` unless you understand the risks of \
not verifying the remote certificate.\
"""

[sources.docker.options.include_containers]
type = "[string]"
common = true
examples = [["my_container_name", "container_prefix", "9b6247364a03"]]
null = true
description = """\
A list of container IDs _or_ names to match against. Prefix matches are \
supported, meaning you can supply just the first few characters of the
container ID or name. If not provided, all containers will be included.\
"""

[sources.docker.options.include_labels]
type = "[string]"
common = true
examples = [["label_key1=label_value1", "label_key2=label_value2"]]
null = true
description = """\
A list of container object labels to match against when filtering running \
containers. This should follow the described label's synatx in [docker object \
labels docs][urls.docker_object_labels].\
"""

[sources.docker.options.include_images]
type = "[string]"
common = true
examples = [["my_image_name", "httpd", "redis"]]
null = true
description = """\
A list of image names to match against. If not provided, \
all images will be included.\
"""

[sources.docker.output.log.fields.container_created_at]
type = "timestamp"
examples = ["2019-11-01T21:15:47.443232Z"]
optional = false
description = """\
A UTC timestamp representing when the container was created.\
"""

[sources.docker.output.log.fields.container_id]
type = "string"
examples = ["9b6247364a03", "715ebfcee040"]
optional = false
description = """\
The Docker container ID that the log was collected from.\
"""

[sources.docker.output.log.fields.container_name]
type = "string"
examples = ["evil_ptolemy", "nostalgic_stallman"]
optional = false
description = """\
The Docker container name that the log was collected from.\
"""

[sources.docker.output.log.fields.image]
type = "string"
examples = ["ubuntu:latest", "busybox", "timberio/vector:latest-alpine"]
optional = false
description = """\
The image name that the container is based on.\
"""

[sources.docker.output.log.fields."`[label-key]`"]
type = "string"
examples = [
  {"com.example.vendor" = "Timber Inc."},
  {"com.example.name" = "Vector"},
  {"com.example.build-date" = "2029-04-12T23:20:50.52Z"},
]
optional = false
description = """\
[Docker object labels][urls.docker_object_labels]. Each label is inserted \
with it's exact key/value pair.\
"""

[sources.docker.output.log.fields.message]
type = "string"
examples = ["Started GET / for 127.0.0.1 at 2012-03-10 14:28:14 +0100"]
optional = false
description = """\
The raw log message, unaltered.\
"""

[sources.docker.output.log.fields.stream]
type = "string"
enum = ["stdout", "stderr"]
optional = false
description = """\
The [standard stream][urls.standard_streams] that the log was collected from.\
"""

[sources.docker.output.log.fields.timestamp]
type = "timestamp"
examples = ["2019-11-01T21:15:47.443232Z"]
optional = false
description = """\
The UTC timestamp extracted from the Docker log event.\
"""
