[sources.file]
beta = true
delivery_guarantee = "best_effort"
guides = []
output_types = ["log"]
resources = []
through_description = "one or more local files"

[sources.file.options.data_dir]
type = "string"
examples = ["/var/lib/vector"]
null = true
description = """\
The directory used to persist file checkpoint positions. By default, the \
global `data_dir` is used. Please make sure the Vector project has write \
permissions to this dir.\
"""

[sources.file.options.include]
type = "[string]"
examples = [["/var/log/nginx/*.log"]]
null = false
description = """\
Array of file patterns to include. [Globbing](#globbing) is supported.\
"""

[sources.file.options.exclude]
type = "[string]"
examples = [["/var/log/nginx/access.log"]]
null = false
description = """\
Array of file patterns to exclude. [Globbing](#globbing) is supported. \
*Takes precedence over the `include` option.*\
"""

[sources.file.options.file_key]
type = "string"
category = "Context"
default = "file"
null = false
section = "context"
description = """\
The key name added to each event with the full path of the file.\
"""

[sources.file.options.glob_minimum_cooldown]
type = "int"
default = 1000
null = false
unit = "milliseconds"
description = """\
Delay between file discovery calls. This controls the interval at which \
Vector searches for files.\
"""

[sources.file.options.host_key]
name = "host_key"
type = "string"
category = "Context"
default = "host"
null = false
section = "context"
description = """\
The key name added to each event representing the current host.\
"""

[sources.file.options.ignore_older]
type = "int"
examples = [86400]
null = true
unit = "seconds"
description = """\
Ignore files with a data modification date that does not exceed this age.\
"""

[sources.file.options.max_line_bytes]
type = "int"
unit = "bytes"
null = true
default = 102400
description = """\
The maximum number of a bytes a line can contain before being \
discarded. This protects against malformed lines or tailing incorrect \
files.\
"""

[sources.file.options.start_at_beginning]
type = "bool"
null = false
default = false
description = """\
When `true` Vector will read from the beginning of new files, when \
`false` Vector will only read new data added to the file.\
"""

[sources.file.options.fingerprinting]
type = "table"
null = true
description = """\
Configuration for how the file source should identify files.\
"""

[sources.file.options.fingerprinting.options.strategy]
type = "string"
enum = ["checksum", "device_and_inode"]
default = "checksum"
null = true
description = """\
Whether to use the content of a file to differentiate it (`checksum`) or the \
storage device and inode (`device_and_inode`). Depending on your log rotation \
strategy, one may be a better fit than the other.\
"""

[sources.file.options.fingerprinting.options.fingerprint_bytes]
type = "int"
default = 256
null = false
unit = "bytes"
relevant_when = {strategy = "checksum"}
description = """\
The number of bytes read off the head of the file to generate a unique \
fingerprint.\
"""

[sources.file.options.fingerprinting.options.ignored_header_bytes]
type = "int"
default = 0
null = false
unit = "bytes"
relevant_when = {strategy = "checksum"}
description = """\
The number of bytes to skip ahead (or ignore) when generating a unique \
fingerprint. This is helpful if all files share a common header.\
"""

[sources.file.options.message_start_indicator]
type = "string"
null = true
examples = ["^(INFO|ERROR)"]
description = """\
When present, Vector will aggregate multiple lines into a single event, using \
this pattern as the indicator that the previous lines should be flushed and \
a new event started. The pattern will be matched against entire lines as \
a regular expression, so remember to anchor as appropriate.\
"""

[sources.file.options.multi_line_timeout]
type = "int"
default = 1000
null = true
unit = "milliseconds"
description = """\
When `message_start_indicator` is present, this sets the amount of time Vector \
will buffer lines into a single event before flushing, regardless of whether \
or not it has seen a line indicating the start of a new message.\
"""

[sources.file.options.max_read_bytes]
type = "int"
default = 2048
null = true
unit = "bytes"
description = """\
An approximate limit on the amount of data read from a single file at a given \
time.\
"""

[sources.file.options.oldest_first]
type = "bool"
default = false
null = true
description = """\
Instead of balancing read capacity fairly across all watched files, prioritize \
draining the oldest files before moving on to read data from younger files.\
"""