[sources.logplex]
title = "Heroku Logplex"
beta = true
common = false
delivery_guarantee = "at_least_once"
function_category = "receive"
output_types = ["log"]
requirements = {}
through_description = "the [Heroku Logplex HTTP Drain protocol][urls.logplex_protocol]"

<%= render("_partials/fields/_component_options.toml", type: "source", name: "logplex") %>

[sources.logplex.options.address]
type = "string"
common = true
examples = ["0.0.0.0:8088"]
required = true
description = """\
The address to accept connections on. The address _must_ include a port.\
"""

<%= render("_partials/fields/_tls_acceptor_options.toml", namespace: "sources.logplex.options", relevant: "") %>
