[sources.stdin]
common = false
delivery_guarantee = "at_least_once"
function_category = "receive"
guides = []
output_types = ["log"]
resources = []
through_description = "standard input (STDIN)"

[sources.stdin.options.max_length]
type = "int"
default = 102400
null = true
unit = "bytes"
description = "The maxiumum bytes size of a message before it is discarded."

[sources.stdin.options.host_key]
type = "string"
category = "Context"
null = false
default = "host"
section = "context"
description = """\
The key name added to each event representing the current host.\
"""

[[sources.stdin.output.log.examples]]
label = "Generic"
input = """\
2019-02-13T19:48:34+00:00 [info] Started GET "/" for 127.0.0.1\
"""
output = """\
{
  "timestamp": <current_timestamp>,
  "message": "2019-02-13T19:48:34+00:00 [info] Started GET "/" for 127.0.0.1",
  "host": "<local_hostname>"
}
"""

[sources.stdin.output.log.fields.host]
type = "string"
examples = ["my.host.com"]
optional = false
description = """\
The local hostname.
"""

[sources.stdin.output.log.fields.message]
type = "string"
examples = ["Started GET / for 127.0.0.1 at 2012-03-10 14:28:14 +0100"]
optional = false
description = """\
The raw message, unaltered.
"""

[sources.stdin.output.log.fields.timestamp]
type = "timestamp"
examples = ["2019-11-01T21:15:47.443232Z"]
optional = false
description = """\
The exact time the event was ingested.\
"""