[sources.stdin]
title = "STDIN"
noun = "STDIN"
beta = false
common = false
delivery_guarantee = "at_least_once"
features = [
  "Accept new line delimited log data through STDIN.",
  "Automatically enrich logs with host-level context.",
]
function_category = "receive"
output_types = ["log"]
requirements = {}
strategies = ["sidecar"]
through_description = "[standard input (STDIN)][urls.stdin]"

<%= render("_partials/fields/_component_options.toml", type: "source", name: "stdin") %>

[sources.stdin.options.max_length]
type = "int"
default = 102400
unit = "bytes"
description = "The maxiumum bytes size of a message before it is discarded."

[sources.stdin.options.host_key]
type = "string"
category = "Context"
default = "host"
description = """\
The key name added to each event representing the current host. This can also \
be globally set via the \
[global `host_key` option][docs.reference.global-options#host_key].\
"""

[[sources.stdin.examples]]
label = "Generic"
body = """\
Given the following input:

```text
2019-02-13T19:48:34+00:00 [info] Started GET "/" for 127.0.0.1
```

A log event will be output with the following structure:

```json
{
  "timestamp": <current_timestamp>,
  "message": "2019-02-13T19:48:34+00:00 [info] Started GET "/" for 127.0.0.1",
  "host": "<local_hostname>"
}
```\
"""

[sources.stdin.fields.log.fields.host]
type = "string"
examples = ["my.host.com"]
required = true
description = """\
The local hostname.
"""

[sources.stdin.fields.log.fields.message]
type = "string"
examples = ["Started GET / for 127.0.0.1 at 2012-03-10 14:28:14 +0100"]
required = true
description = """\
The raw message, unaltered.
"""

[sources.stdin.fields.log.fields.timestamp]
type = "timestamp"
examples = ["2019-11-01T21:15:47.443232Z"]
required = true
description = """\
The exact time the event was ingested.\
"""
