[sources.tcp]
common = false
delivery_guarantee = "best_effort"
function_category = "receive"
guides = []
output_types = ["log"]
resources = []
through_description = "the TCP protocol"

[sources.tcp.options.address]
type = "string"
common = true
examples = ["0.0.0.0:9000", "systemd", "systemd#3"]
null = false
description = """The address to listen for connections on, \
or "systemd#N" to use the Nth socket passed by systemd socket activation. \
"""

[sources.tcp.options.host_key]
name = "host_key"
type = "string"
category = "Context"
null = false
default = "host"
section = "context"
description = """\
The key name added to each event representing the current host.\
"""

[sources.tcp.options.max_length]
type = "int"
default = 102400
null = true
unit = "bytes"
description = """\
The maximum bytes size of incoming messages before they are discarded.\
"""

[sources.tcp.options.shutdown_timeout_secs]
type = "int"
default = 30
null = false
unit = "seconds"
description = """\
The timeout before a connection is forcefully closed during shutdown.\
"""

[[sources.tcp.output.log.examples]]
label = "Generic"
input = """\
2019-02-13T19:48:34+00:00 [info] Started GET "/" for 127.0.0.1\
"""
output = """\
{
  "timestamp": <current_timestamp>,
  "message": "2019-02-13T19:48:34+00:00 [info] Started GET "/" for 127.0.0.1",
  "host": "<upstream_hostname>"
}
"""

[sources.tcp.output.log.fields.host]
type = "string"
examples = ["my.host.com"]
optional = false
description = """\
The upstream hostname.
"""

[sources.tcp.output.log.fields.message]
type = "string"
examples = ["Started GET / for 127.0.0.1 at 2012-03-10 14:28:14 +0100"]
optional = false
description = """\
The raw message, unaltered.
"""

[sources.tcp.output.log.fields.timestamp]
type = "timestamp"
examples = ["2019-11-01T21:15:47.443232Z"]
optional = false
description = """\
The exact time the event was ingested.
"""
