[sources.vector]
title = "Vector"
noun = "Vector"
beta = true
common = false
delivery_guarantee = "best_effort"
features = [
  "Accept data from another upstream Vector instance.",
]
function_category = "receive"
output_types = ["log", "metric"]
requirements.network_port = "9000"
strategies = ["service"]
through_description = "another upstream [`vector` sink][docs.sinks.vector]"

<%= render("_partials/fields/_component_options.toml", type: "source", name: "vector") %>

[sources.vector.options.address]
type = "string"
common = true
examples = ["0.0.0.0:9000", "systemd", "systemd#1"]
required = true
description = """\
The TCP address to listen for connections on, or `systemd#N to use the Nth \
socket passed by systemd socket activation. If an address is used it _must_ \
include a port.
"""

[sources.vector.options.shutdown_timeout_secs]
type = "int"
default = 30
unit = "seconds"
description = """\
The timeout before a connection is forcefully closed during shutdown.\
"""

<%= render("_partials/fields/_tls_acceptor_options.toml", namespace: "sources.vector.options", relevant: "") %>
