#
# Subdomains
#

[[redirects]]
  from = "https://vector-project.netlify.com/*"
  to = "https://vector.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://chat.vector.dev/*"
  to = "https://gitter.im/timberio-vector/community"
  status = 302
  force = true

[[redirects]]
  from = "https://sh.vector.dev/*"
  to = "http://sh.vector.dev.s3-website-us-east-1.amazonaws.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://test-results.vector.dev/*"
  to = "http://test-results.vector.dev.s3-website-us-east-1.amazonaws.com/:splat"
  status = 200
  force = true

#
# Old docs site
#

[[redirects]]
  from = "https://docs.vector.dev/usage/administration/stopping"
  to = "https://vector.dev/docs/administration/process-management/#stopping"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.vector.dev/usage/administration/reloading"
  to = "https://vector.dev/docs/administration/process-management/#reloading"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.vector.dev/usage/administration/starting"
  to = "https://vector.dev/docs/administration/process-management/#starting"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.vector.dev/usage/configuration"
  to = "https://vector.dev/docs/setup/configuration/"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.vector.dev/usage/configuration/*"
  to = "https://vector.dev/docs/reference/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.vector.dev/*"
  to = "https://vector.dev/docs/:splat"
  status = 301
  force = true

#
# Internal redirects
#

[[redirects]]
  from = "/docs/"
  to = "/docs/about/what-is-vector/"
  status = 302
  force = true

[[redirects]]
  from = "/docs/reference/sinks/tcp/"
  to = "/docs/reference/sinks/socket/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/reference/sources/tcp/"
  to = "/docs/reference/sources/socket/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/reference/sources/udp/"
  to = "/docs/reference/sources/socket/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/setup/installation/containers/"
  to = "/docs/setup/installation/platforms/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/setup/installation/containers/docker/"
  to = "/docs/setup/installation/platforms/docker"
  status = 301
  force = true

[[redirects]]
  from = "/download/"
  to = "/releases/latest/download/"
  status = 302
  force = true

[[redirects]]
  from = "/mailing_list/"
  to = "/community/"
  status = 301
  force = true

  [[redirects]]
  from = "/releases/"
  to = "/releases/latest/download/"
  status = 302
  force = true
