version: '3'

services:
  eventstoredb:
    image: docker.io/eventstore/eventstore:${CONFIG_VERSION}
    command: --insecure --stats-period-sec=1
    volumes:
    - ../../../tests/data:/etc/vector:ro
