data_dir = "/var/lib/vector"

##
## Sources
##

[sources.internal_metrics]
type = "internal_metrics"

[sources.syslog]
type = "syslog"
address = "0.0.0.0:8282"
max_length = 1_500_000
mode = "tcp"

##
## Transforms
## 

[transforms.remap]
type = "remap"
inputs = ["syslog"]
source = """
    . = parse_syslog!(.message)
"""

[transforms.log2metric]
type = "log_to_metric"
inputs = ["remap"]

    [[transforms.log2metric.metrics]]
    type = "gauge"
    field = "procid"

##
## Sinks
##

[sinks.prometheus]
type = "prometheus_exporter"
inputs = ["internal_metrics"]
address = "0.0.0.0:9090"

[sinks.humio_logs]
type = "humio_logs"
inputs = ["syslog"]
endpoint = "http://http-blackhole:8080"
encoding = "json"
token = "humio_token"
healthcheck.enabled = false
