# `add_fields` Transform Example
# ------------------------------------------------------------------------------
# A simple example demonstrating the `add_fields` transform
# Docs: https://docs.vector.dev/usage/configuration/transforms/add_fields

[transforms.my_add_fields_transform]
  # REQUIRED - General
  type = "add_fields" # must be: add_fields
  inputs = ["\"my-source-id\""]

  # REQUIRED - Fields
  [transforms.my_add_fields_transform.fields]
    my_string_field = "string value"
    my_int_field = 1
    my_float_field = 1.2
    my_bool_field = true
    my_timestamp_field = 1979-05-27T00:32:00.999998-07:00
    my_table_field = {key1 = "value1", key2 = "value2"}
