# `field_filter` Transform Example
# ------------------------------------------------------------------------------
# A simple example demonstrating the `field_filter` transform
# Docs: https://docs.vector.dev/usage/configuration/transforms/field_filter

[transforms.my_field_filter_transform]
  # REQUIRED - General
  type = "field_filter" # must be: field_filter
  inputs = ["\"my-source-id\""]
  field = "file"
  value = "/var/log/nginx.log"
