# `lua` Transform Example
# ------------------------------------------------------------------------------
# A simple example demonstrating the `lua` transform
# Docs: https://docs.vector.dev/usage/configuration/transforms/lua

[transforms.my_lua_transform]
  # REQUIRED - General
  type = "lua" # must be: lua
  inputs = ["my-source-id"]

  # OPTIONAL - General
  search_dirs = ["/etc/vector/lua"] # no default
  source = """
  require("script") # a `script.lua` file must be in your `search_dirs`

  if event["host"] == nil then
    local f = io.popen ("/bin/hostname")
    local hostname = f:read("*a") or ""
    f:close()
    hostname = string.gsub(hostname, "\n$", "")
    event["host"] = hostname
  end
  """
