# `tokenizer` Transform Example
# ------------------------------------------------------------------------------
# A simple example demonstrating the `tokenizer` transform
# Docs: https://docs.vector.dev/usage/configuration/transforms/tokenizer

[transforms.my_tokenizer_transform]
  # REQUIRED - General
  type = "tokenizer" # must be: tokenizer
  inputs = ["\"my-source-id\""]
  field_names = ["\"timestamp\"", "\"level\"", "\"message\""]

  # OPTIONAL - General
  drop_field = true # default
  field = "message" # default

  # OPTIONAL - Types
  [transforms.my_tokenizer_transform.types]
    status = "int"
    duration = "float"
    success = "bool"
    timestamp = "timestamp|%s" # unix
    timestamp = "timestamp|%+" # iso8601 (date and time)
    timestamp = "timestamp|%F" # iso8601 (date)
    timestamp = "timestamp|%a %b %e %T %Y" # custom strftime format
