apiVersion: v1
name: vector
type: application
icon: https://vector.dev/press/vector-icon.svg
description: A Helm chart to collect Kubernetes logs with Vector
version: "0.1.0"
appVersion: "0.10"
home: https://vector.dev/
sources:
  - https://github.com/timberio/vector/
maintainers:
  - name: Vector Contributors
    email: vector@timber.io
