name: Benchmark Suite

on:
  pull_request: {}
  push:
    branches:
      - master
  workflow_dispatch:

env:
  VERBOSE: true
  AWS_ACCESS_KEY_ID: "dummy"
  AWS_SECRET_ACCESS_KEY: "dummy"
  CI: true

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  bench:
    name: Bench - Linux
    runs-on: ubuntu-20.04
    # Allow benchmarks show regressions until we can refine the thresholds for
    # regression to reduce false positives.
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - run: make ci-sweep
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Download baseline benchmarks
        uses: dawidd6/action-download-artifact@f2f4c0c7333a76ab3aff16e7b2cf4ed7f5a74556
        continue-on-error: true
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: benches.yml
          branch: master
          name: criterion
          path: target
      - name: Check if there were master artifacts
        run: |
          test -f target/criterion.zip || echo "::warning::No master benchmark artifacts could be fetched for comparison."
      - run: unzip target/criterion.zip
        continue-on-error: true
      - run: sudo bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: make slim-builds
      - name: Run benchmarks
        run: |
          mkdir -p target/criterion
          make bench | tee target/criterion/out
      - run: zip --recurse-paths target/criterion.zip target/criterion
      - uses: actions/upload-artifact@v2
        with:
          name: "criterion"
          path: "./target/criterion.zip"
      - run: cat target/criterion/out | scripts/check-criterion-output.sh

  master-failure:
    name: master-failure
    if: failure() && github.ref == 'refs/heads/master'
    needs:
      - cancel-previous
      - bench
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@0.3.0
      with:
        args: "Master benchmarks failed: <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}>"
