name: Deploy Vector Preview Sites

on:
  pull_request:
    types: [opened, reopened, syncronize]

jobs:
  deploy_vecotr_preview_site:
    uses: .github/workflows/create_preview_sites.yml@master
    with:
      APP_ID: "d1a7j77663uxsc"
      APP_NAME: "vector.dev"

  deploy_rust_doc_preview_site:
    uses: .github/workflows/create_preview_sites.yml@master
    with:
      APP_ID: "d1hoyoksbulg25"
      APP_NAME: "Rust Doc"

  deploy_vrl_playground_preview_site:
    uses: .github/workflows/create_preview_sites.yml@master
    with:
      APP_ID: "d2lr4eds605rpz"
      APP_NAME: "VRL Playground"
