name: Ensure Cache

on:
  push:
    paths:
      - './scripts/environment/prepare.sh'
      - './.github/actions/cache/**'
  workflow_call:

# Wrapper workflow
concurrency:
  group: cache-${{ github.event.number || github.event.merge_group.head_sha || github.sha }}
  cancel-in-progress: false

jobs:
  ensure-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run cache action
        uses: ./.github/actions/cache
        with:
          check-only: true
