# A workflow that runs [cargo-hack](https://github.com/taiki-e/cargo-hack)
# across our feature flags. We do not run a powerset as there's too many
# features to fit all that in memory.
name: cargo_hack

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  AUTOINSTALL: true
  VERBOSE: true
  CI: true
  DEBIAN_FRONTEND: noninteractive

jobs:
  hack:
    runs-on: [self-hosted, linux, x64, general]
    name: Cargo Hack Check
    steps:
      - uses: actions/checkout@v2
      - run: sudo bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: cargo install cargo-hack
      - run: cargo hack check --each-feature

  # Temporarily disabled until we achieve a clean nightly run of cargo-hack,
  # which is blocked behind known failures.

  # cargo-hack-failure:
  #   name: cargo-hack-failure
  #   if: failure() && github.ref == 'refs/heads/master'
  #   needs:
  #     - hack
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - name: Discord notification
  #     env:
  #       DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  #     uses: Ilshidur/action-discord@0.3.0
  #     with:
  #       args: "Master cargo-hack failed: <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}>"
