name: check

on:
  pull_request: {}

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EmbarkStudios/cargo-deny-action@v0
        with:
          command: check advisories

  component-features:
    runs-on: ubuntu-latest
    env:
      USE_CONTAINER: none
    steps:
      - uses: actions/checkout@v1
      - run: sudo apt install -y python3-pip python3-setuptools python3-wheel
      - run: sudo python3 -m pip install remarshal
      - run: make check-component-features

  code-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make check-code
        env:
          PASS_RUSTFLAGS: "-D warnings"

  code-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - env:
          USE_CONTAINER: none
          RUSTFLAGS: "-D warnings"
        run: cargo check --no-default-features --features default-msvc

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make check-fmt
        env:
          PASS_RUSTFLAGS: "-D warnings"

  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make check-generate

  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1.0.0
      - run: make check-markdown

  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Checklist
        uses: wyozi/contextual-qa-checklist-action@master
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          input-file: .github/checklist.yml

  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make check-version

  blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make check-blog
