name: ci
on:
  push:
    branches:
    - master
  pull_request: {}
jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: EmbarkStudios/cargo-deny-action@v0
      with:
        command: "check advisories"
  test-behavior:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: "cd tests && make test-behavior"
  check-component-features:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: "cd tests && make check-component-features"
  check-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: "make check-code"
        env:
          PASS_RUSTFLAGS: "-D warnings"
  check-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: "make check-fmt"
        env:
          PASS_RUSTFLAGS: "-D warnings"
  check-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: "make check-fmt"
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: "make check-version"
  check-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: "make check-blog"
  test-stable:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
      TEST_LOG: debug
      AWS_ACCESS_KEY_ID: fake-aws-key
      AWS_SECRET_ACCESS_KEY: fake-aws-key
      TARGET: x86_64-unknown-linux-musl
    steps:
      - checkout
      - run: sudo apt install -y docker-compose docker-io
      - run:
          name: Build tests
          command: |
            cargo test --all --no-default-features --features default-musl,docker --no-run --target $TARGET
      - run:
          name: Start dependencies
          command: |
            docker-compose pull
            docker-compose up -d splunk
            sleep 30 # Splunk crashes when started simultaneously with other services
            docker-compose up -d test-runtime-deps
            sleep 180
      - run:
          name: Run tests
          command: |
            find ./target/$TARGET -maxdepth 2 -type f -executable -name '*-*' | sh -e


## Kubernetes
# Build exectuables in parallel, and then tests on different Kubernetes versions in parallel.

  # Builds vector executable that will be tested.
  build-vector-kubernetes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --no-default-features  --features "sources-kubernetes transforms-kubernetes sinks-console"
    - name: Save vector
      uses: actions/upload-artifact@v1
      with:
        name: builds
        path: ./target/release/vector

  # Builds vector executable that will be testing.
  build-test-vector-kubernetes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo test --lib --features "sources-kubernetes transforms-kubernetes kubernetes-integration-tests" --no-run
    - name: Rename test executable
      run: find -regex "./target/debug/deps/vector-[0-9a-fA-F]+" -exec mv {} ./target/debug/deps/vector-test ';'
    - name: Save vector
      uses: actions/upload-artifact@v1
      with:
        name: builds
        path: ./target/debug/deps/vector-test

  # Uses two previosuly builded vector executables to do testing.
  test-kubernetes:
    needs: [build-vector-kubernetes,build-test-vector-kubernetes]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kube: [1.14.10, 1.17.2]
    steps:
    - name: Load vector
      uses: actions/download-artifact@v1
      with:
        name: builds
    - uses: opsgang/ga-setup-minikube@v0.1.1
      with:
        minikube-version: 1.9.1
        k8s-version: ${{ matrix.kube }}
    - name: Start local repository
      run: docker run -d -p 5000:5000 --restart=always --name registry registry:2
    - name: Start minikube
      run: sudo CHANGE_MINIKUBE_NONE_USER=true /home/runner/bin/minikube start --vm-driver=none --kubernetes-version=v${{ matrix.kube }}
    - name: Build & push image
      run: |
        docker build -t "localhost:5000/vector_test:latest" -f - . << EOF
        FROM buildpack-deps:18.04-curl
        COPY ./builds/vector /usr/local/bin
        RUN chmod +x /usr/local/bin/vector
        ENTRYPOINT ["/usr/local/bin/vector"]
        EOF
        docker push localhost:5000/vector_test:latest
    - name: Make test binary executable
      run: chmod +x ./builds/vector-test
    - name: Run kubernetes integration tests
      run: KUBE_TEST_IMAGE=localhost:5000/vector_test:latest TEST_LOG=debug ./builds/vector-test --test-threads=1 kubernetes

