name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request:
  pull_request_target:
    types: [opened, closed, synchronize]

permissions:
  contents: read
  pull-requests: write
  id-token: write # Needed to federate tokens.
  actions: write

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - uses: DataDog/dd-octo-sts-action@08f2144903ced3254a3dafec2592563409ba2aa0 # v1.0.1
        id: octo-sts
        with:
          scope: DataDog/cla-signatures
          policy: self.write-signatures-vector

      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target' || github.event_name == 'pull_request'
        uses: contributor-assistant/github-action@ca4a40a7d1004f18d9960b404b97e5f30a505a08 # v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ steps.octo-sts.outputs.token }}
        with:
          path-to-signatures: 'cla.json'
          path-to-document: 'https://gist.github.com/bits-bot/55bdc97a4fdad52d97feb4d6c3d1d618' # e.g. a CLA or a DCO document
          branch: 'vector'
          remote-repository-name: cla-signatures
          remote-organization-name: DataDog

         # the followings are the optional inputs - If the optional inputs are not given, then default values will be taken
          #allowlist: user1,bot*
          #create-file-commit-message: 'For example: Creating file for storing CLA Signatures'
          #signed-commit-message: 'For example: $contributorName has signed the CLA in $owner/$repo#$pullRequestNo'
          #custom-notsigned-prcomment: 'pull request comment with Introductory message to ask new contributors to sign'
          #custom-pr-sign-comment: 'The signature to be committed in order to sign the CLA'
          #custom-allsigned-prcomment: 'pull request comment when all contributors has signed, defaults to **CLA Assistant Lite bot** All Contributors have signed the CLA.'
          #lock-pullrequest-aftermerge: false - if you don't want this bot to automatically lock the pull request after merging (default - true)
