# Integration Test Comment
#
# This workflow runs one or more integration tests triggered by a comment in a PR.
# The comment include '/ci-run-integration'.
# Then, any if the integration names will trigger that specific integration.
# 'all' will trigger every integration to run.
# The order does not matter and can be anywhere inside the comment body.
#
# Examples:
#
# 1. Run a single integration test:
#
#     /ci-run-integration amqp
#
# 2. Run three specific integration tests:
#
#     /ci-run-integration dnstap redis amqp
#
# 3. Run all integration tests:
#
#     /ci-run-integration all

name: Integration Test Comment

on:
  issue_comment:
    types: [created]

env:
  AWS_ACCESS_KEY_ID: "dummy"
  AWS_SECRET_ACCESS_KEY: "dummy"
  AXIOM_TOKEN: ${{ secrets.AXIOM_TOKEN }}
  TEST_APPSIGNAL_PUSH_API_KEY: ${{ secrets.TEST_APPSIGNAL_PUSH_API_KEY }}
  CONTAINER_TOOL: "docker"
  DD_ENV: "ci"
  DD_API_KEY: ${{ secrets.DD_API_KEY }}
  RUST_BACKTRACE: full
  TEST_LOG: vector=debug
  VERBOSE: true
  CI: true
  PROFILE: debug

jobs:
  prep-pr:
    name: (PR comment) Signal pending to PR
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/ci-run-integration') || contains(github.event.comment.body, '/ci-run-all')
    steps:
      - name: Get PR comment author
        id: comment
        uses: tspascoal/get-user-teams-membership@v2
        with:
          username: ${{ github.actor }}
          team: 'Vector'
          GITHUB_TOKEN: ${{ secrets.GH_PAT_ORG }}

      - name: Validate author membership
        if: steps.comment.outputs.isTeamMember == 'false'
        run: exit 1

      - name: (PR comment) Get PR branch
        uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch

      - name: (PR comment) Set latest commit status as pending
        uses: myrotvorets/set-commit-status-action@v1.1.7
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending

  test-integration:
    uses: ./.github/workflows/integration-test.yml
    with:
      if: ${{ matrix.run.if }}
      test_name: ${{ matrix.run.test_name }}
    needs: prep-pr
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        run:
          - test_name: 'amqp'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-amqp')          || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'appsignal'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-appsignal')     || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'aws'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-aws')           || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'axiom'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-axiom')         || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'azure'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-azure')         || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'clickhouse'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-clickhouse')    || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'databend'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-databend')      || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'datadog-agent'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-datadog')       || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'datadog-logs'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-datadog')       || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'datadog-metrics'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-datadog')       || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'datadog-traces'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-datadog')       || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'dnstap'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-dnstap')        || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'docker-logs'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-docker-logs')   || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'elasticsearch'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-elasticsearch') || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'eventstoredb'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-eventstoredb')  || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'fluent'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-fluent')        || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'gcp'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-gcp')           || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'humio'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-humio')         || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'http-client'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-http-client')   || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'influxdb'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-influxdb')      || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'kafka'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-kafka')         || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'logstash'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-logstash')      || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'loki'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-loki')          || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'mongodb'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-mongodb')       || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'nats'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-nats')          || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'nginx'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-nginx')         || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'opentelemetry'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-opentelemetry') || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'postgres'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-postgres')      || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'prometheus'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-prometheus')    || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'pulsar'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-pulsar')        || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'redis'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-redis')         || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'shutdown'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-shutdown')      || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'splunk'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-splunk')        || contains(github.event.comment.body, '/ci-run-all') }}
          - test_name: 'webhdfs'
            if: ${{ contains(github.event.comment.body, '/ci-run-integration-webhdfs')       || contains(github.event.comment.body, '/ci-run-all') }}

  update-pr-status:
    name: Signal result to PR
    runs-on: ubuntu-latest
    needs: test-integration
    if: always() && (contains(github.event.comment.body, '/ci-run-integration') || contains(github.event.comment.body, '/ci-run-all'))
    steps:
      - name: Validate issue comment
        if: github.event_name == 'issue_comment'
        uses: tspascoal/get-user-teams-membership@v2
        with:
          username: ${{ github.actor }}
          team: 'Vector'
          GITHUB_TOKEN: ${{ secrets.GH_PAT_ORG }}

      - name: (PR comment) Get PR branch
        uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch

      - name: (PR comment) Submit PR result as ${{ needs.test-integration.result }}
        uses: myrotvorets/set-commit-status-action@v1.1.7
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ needs.test-integration.result }}
