name: Check minimum supported Rust version (MSRV)

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      checkout_ref:
        description: "Git ref (branch, tag or SHA) to check out"
        required: false
        type: string

env:
  RUST_BACKTRACE: full
  CI: true
  PROFILE: debug

jobs:
  check-msrv:
    runs-on: ubuntu-24.04
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.checkout_ref }}
      - uses: ./.github/actions/setup
        with:
          rust: true
          cargo-msrv: true
      - run: cargo msrv verify
