name: Check minimum supported Rust version (MSRV)

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      checkout_ref:
        description: "Git ref (branch, tag or SHA) to check out"
        required: false
        type: string

env:
  RUST_BACKTRACE: full
  CI: true
  PROFILE: debug

permissions:
  contents: read

jobs:
  check-msrv:
    runs-on: ubuntu-24.04
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.checkout_ref }}
      - uses: ./.github/actions/setup
        with:
          rust: true
          protoc: true
          libsasl2: true
          cargo-msrv: true
      - run: cargo msrv verify
