name: Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"  # Runs at 5:00 AM UTC

jobs:
  Nightly:
    uses: ./.github/workflows/publish.yml
    with:
      git_ref: ${{ github.ref }}
      channel: nightly
    secrets: inherit
