name: nightly

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

env:
  AUTOINSTALL: true
  CHANNEL: nightly
  VERBOSE: true
  CI: true

jobs:
  build-x86_64-unknown-linux-musl-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make ci-sweep
      - env:
          PASS_FEATURES: "default-cmake"
        run: make package-x86_64-unknown-linux-musl
      - uses: actions/upload-artifact@v1
        with:
          name: "vector-x86_64-unknown-linux-musl.tar.gz"
          path: "./target/artifacts/vector-x86_64-unknown-linux-musl.tar.gz"

  build-x86_64-unknown-linux-gnu-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make ci-sweep
      - env:
          PASS_FEATURES: "default"
        run: make package-x86_64-unknown-linux-gnu-all
      - uses: actions/upload-artifact@v1
        with:
          name: "vector-x86_64-unknown-linux-gnu.tar.gz"
          path: "./target/artifacts/vector-x86_64-unknown-linux-gnu.tar.gz"
      - uses: actions/upload-artifact@v1
        with:
          name: "vector-amd64.deb"
          path: "./target/artifacts/vector-amd64.deb"
      - uses: actions/upload-artifact@v1
        with:
          name: "vector-x86_64.rpm"
          path: "./target/artifacts/vector-x86_64.rpm"

  build-aarch64-unknown-linux-musl-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make ci-sweep
      - env:
          DOCKER_PRIVILEGED: "true"
          PASS_FEATURES: "default-cmake"
        run: make package-aarch64-unknown-linux-musl-all
      - uses: actions/upload-artifact@v1
        with:
          name: "vector-aarch64-unknown-linux-musl.tar.gz"
          path: "./target/artifacts/vector-aarch64-unknown-linux-musl.tar.gz"
      - uses: actions/upload-artifact@v1
        with:
          name: "vector-arm64.deb"
          path: "./target/artifacts/vector-arm64.deb"
      - uses: actions/upload-artifact@v1
        with:
          name: "vector-aarch64.rpm"
          path: "./target/artifacts/vector-aarch64.rpm"

  build-x86_64-apple-darwin-packages:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1
      - name: "Upgrade bash"
        run: brew install bash
      - name: "Install realpath dependency"
        run: brew install coreutils
      - name: "Build archive"
        env:
          TARGET: "x86_64-apple-darwin"
          NATIVE_BUILD: true
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          make package
      - uses: actions/upload-artifact@v1
        with:
          name: "vector-x86_64-apple-darwin.tar.gz"
          path: "./target/artifacts/vector-x86_64-apple-darwin.tar.gz"

  build-x86_64-pc-windows-msvc-packages:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
      - name: "Download Perl"
        shell: bash
        env:
          VERSION: "5.30.0.1"
          SHA256SUM: "459de13a284a4c83213208c9caa1c372c81136b6e863a3f13d42f631048e0b12" # we need to verify checksum because strawberryperl.com doesn't support HTTPS
        run: |
          curl -sSf http://strawberryperl.com/download/$VERSION/strawberry-perl-$VERSION-64bit.msi > perl-installer.msi
          echo "$SHA256SUM perl-installer.msi" | sha256sum --check --status
      - name: "Install Perl"
        shell: cmd # msiexec fails when called from bash
        run: |
          msiexec /quiet /i perl-installer.msi
          del perl-installer.msi
      - name: "Download CMake"
        shell: bash
        env:
          VERSION: "3.15.5"
        run: |
          curl -sSfL https://github.com/Kitware/CMake/releases/download/v$VERSION/cmake-$VERSION-win64-x64.msi > cmake-installer.msi
      - name: "Install CMake"
        shell: cmd # msiexec fails when called from bash
        run: |
          msiexec /quiet /i cmake-installer.msi
          del cmake-installer.msi
      - name: "Install Wix"
        shell: bash
        run: |
          mkdir -p /c/wix
          cd /c/wix
          curl -sSfL https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip > wix-binaries.zip
          unzip wix-binaries.zip
          rm wix-binaries.zip
      - name: "Build archive"
        shell: bash
        run: |
          export PATH="$HOME/.cargo/bin:/c/Strawberry/perl/bin:/c/Program Files/CMake/bin:$PATH"
          export RUSTFLAGS=-Ctarget-feature=+crt-static
          export FEATURES="default-msvc"
          export ARCHIVE_TYPE="zip"
          export KEEP_SYMBOLS="true"
          export RUST_LTO=""
          export TARGET="x86_64-pc-windows-msvc"
          export NATIVE_BUILD="true"
          make package
      - name: "Build package"
        shell: bash
        run: |
          export PATH="/c/wix:$PATH"
          ./scripts/package-msi.sh
      - uses: actions/upload-artifact@v1
        with:
          name: "vector-x86_64-pc-windows-msvc.zip"
          path: "./target/artifacts/vector-x86_64-pc-windows-msvc.zip"
      - uses: actions/upload-artifact@v1
        with:
          name: "vector-x64.msi"
          path: "./target/artifacts/vector-x64.msi"

  release-docker:
    runs-on: ubuntu-latest
    needs:
      - build-x86_64-unknown-linux-musl-packages
      - build-aarch64-unknown-linux-musl-packages
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v1
        with:
          name: vector-x86_64-unknown-linux-musl.tar.gz
          path: target/artifacts
      - uses: actions/download-artifact@v1
        with:
          name: vector-aarch64-unknown-linux-musl.tar.gz
          path: target/artifacts
      - uses: actions/download-artifact@v1
        with:
          name: vector-amd64.deb
          path: target/artifacts
      - uses: actions/download-artifact@v1
        with:
          name: vector-arm64.deb
          path: target/artifacts
      - env:
          DOCKER_USERNAME: "${{ secrets.CI_DOCKER_USERNAME }}"
          DOCKER_PASSWORD: "${{ secrets.CI_DOCKER_PASSWORD }}"
          PLATFORM: "linux/amd64,linux/arm64"
        run: |
          ./scripts/upgrade-docker.sh
          export VERSION=$(make version)
          make release-docker

  release-s3:
    runs-on: ubuntu-latest
    needs:
      - build-x86_64-unknown-linux-gnu-packages
      - build-x86_64-unknown-linux-musl-packages
      - build-aarch64-unknown-linux-musl-packages
      - build-x86_64-apple-darwin-packages
      - build-x86_64-pc-windows-msvc-packages
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v1
        with:
          name: vector-x86_64-unknown-linux-gnu.tar.gz
          path: target/artifacts
      - uses: actions/download-artifact@v1
        with:
          name: vector-x86_64-unknown-linux-musl.tar.gz
          path: target/artifacts
      - uses: actions/download-artifact@v1
        with:
          name: vector-aarch64-unknown-linux-musl.tar.gz
          path: target/artifacts
      - uses: actions/download-artifact@v1
        with:
          name: vector-amd64.deb
          path: target/artifacts
      - uses: actions/download-artifact@v1
        with:
          name: vector-arm64.deb
          path: target/artifacts
      - uses: actions/download-artifact@v1
        with:
          name: vector-x86_64-apple-darwin.tar.gz
          path: target/artifacts
      - uses: actions/download-artifact@v1
        with:
          name: vector-x86_64-pc-windows-msvc.zip
          path: target/artifacts
      - uses: actions/download-artifact@v1
        with:
          name: vector-x64.msi
          path: target/artifacts
      - uses: actions/download-artifact@v1
        with:
          name: vector-x86_64.rpm
          path: target/artifacts
      - uses: actions/download-artifact@v1
        with:
          name: vector-aarch64.rpm
          path: target/artifacts
      - env:
          AWS_ACCESS_KEY_ID: "${{ secrets.CI_AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}"
        run: make release-s3

  release-cloudsmith:
    runs-on: ubuntu-latest
    needs:
      - build-x86_64-unknown-linux-gnu-packages
      - build-aarch64-unknown-linux-musl-packages
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v1
        with:
          name: vector-amd64.deb
          path: target/artifacts
      - uses: actions/download-artifact@v1
        with:
          name: vector-arm64.deb
          path: target/artifacts
      - uses: actions/download-artifact@v1
        with:
          name: vector-x86_64.rpm
          path: target/artifacts
      - uses: actions/download-artifact@v1
        with:
          name: vector-aarch64.rpm
          path: target/artifacts
      - name: Push amd64 deb
        id: push-deb-amd64
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "deb"
          owner: "timber"
          repo: "vector-nightly"
          distro: "any-distro"
          release: "any-version"
          republish: "true"
          file: "target/artifacts/vector-amd64.deb"
      - name: Push arm64 deb
        id: push-deb-arm64
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "deb"
          owner: "timber"
          repo: "vector-nightly"
          distro: "any-distro"
          release: "any-version"
          republish: "true"
          file: "target/artifacts/vector-arm64.deb"
      - name: Push x86_64 RPM
        id: push-rpm-x86_64
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "rpm"
          owner: "timber"
          repo: "vector-nightly"
          distro: "any-distro"
          release: "any-version"
          republish: "true"
          file: "target/artifacts/vector-x86_64.rpm"
      - name: Push aarch64 RPM
        id: push-rpm-aarch64
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "rpm"
          owner: "timber"
          repo: "vector-nightly"
          distro: "any-distro"
          release: "any-version"
          republish: "true"
          file: "target/artifacts/vector-aarch64.rpm"

  release-helm:
    runs-on: ubuntu-latest
    needs:
      # This is not strictly required, but ensures that Helm Chart doesn't
      # appear before the image it refers to.
      - release-docker
    steps:
      - uses: actions/checkout@v1
      - name: Install Helm
        run: scripts/environment/setup-helm.sh
      - name: Release Helm Chart
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.CI_AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}"
        run: make release-helm

  nightly-failure:
    name: nightly-failure
    if: failure()
    needs:
      - build-x86_64-unknown-linux-gnu-packages
      - build-x86_64-unknown-linux-musl-packages
      - build-aarch64-unknown-linux-musl-packages
      - build-x86_64-apple-darwin-packages
      - build-x86_64-pc-windows-msvc-packages
      - release-docker
      - release-s3
      - release-cloudsmith
      - release-helm
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@0.3.0
      with:
        args: "Nightly failed: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
