name: Publish Docs If Updated

on:
  pull_request:
    types: [closed, synchronize, opened, reopened]
    branches:
      - master

jobs:
  check-docs-diff:
    runs-on: macos-latest
    outputs:
      diff: ${{ steps.git-diff.outputs.diff }}
    steps:
      - name: Checkout Vector
        uses: actions/checkout@v2

      - name: Check MD Diff
        id: git-diff
        uses: technote-space/get-diff-action@v3
        with:
          PREFIX_FILTER: |
            docs

  build:
    runs-on: macos-latest
    needs: check-docs-diff
    if: ${{ needs.checkMdDiff.outputs.diff }}
    steps:
      - name: Clone Vector
        uses: actions/checkout@v2
        with:
          repository: timberio/vector
          ref: ${{ github.ref }}
          path: vector

      - name: Clone Vector Website
        uses: actions/checkout@v2
        with:
          # timberio/vector-website and gatsby-docs respectively
          repository: "${{ secrets.VECTOR_WEBSITE_REPO }}"
          ref: ${{ secrets.NETLIFY_VECTOR_WEBSITE_REF }}"
          path: vector-website

      - name: Setup Cue
        run: brew install cuelang/tap/cue

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Install Dependencies
        working-directory: ./vector-website
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
          yarn install
          cd ./plugins/gatsby-plugin-graphql-codegen && yarn install

      - name: Build Site
        run: cd ./vector-website && yarn run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: gatsby-build
          path: ./vector-website/public

  preview:
    runs-on: macos-latest
    needs: build
    if: github.event.action != 'closed'
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: gatsby-build

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Install Dependencies
        run: npm install -g netlify-cli

      - name: Deploy Preview
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --dir=./ --message="Preview from vector:${{ github.head_ref }}@${{ github.sha }} With ${{ secrets.NETLIFY_VECTOR_WEBSITE_REPO }}@${{ secrets.NETLIFY_VECTOR_WEBSITE_REF }}"

  publish:
    runs-on: macos-latest
    needs: build
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: gatsby-build

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Install Dependencies
        run: npm install -g netlify-cli

      - name: Deploy Production
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --dir=./ --prod --message="Deploy from vector:${{ github.head_ref }}@${{ github.sha }} With ${{ secrets.NETLIFY_VECTOR_WEBSITE_REPO }}@${{ secrets.NETLIFY_VECTOR_WEBSITE_REF }}"
