# Build soak test infra
#
# This workflow builds our soak test infrastructure. The image here is
# built on a push to master branch that update the 'lib/soak' directory.
name: Soak Infra

on:
  pull_request:
    paths:
      - 'lib/soak'
      - 'soaks/Dockerfile'
      - 'soaks/Dockerfile.builder'
      - '.github/workflows/soak_infra.yml'
  push:
    branches:
      - master
    paths:
      - 'lib/soak'
      - 'soaks/Dockerfile'
      - 'soaks/Dockerfile.builder'
      - '.github/workflows/soak_infra.yml'

jobs:
  cancel-previous:
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: styfle/cancel-workflow-action@0.10.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          all_but_latest: true # can cancel workflows scheduled later

  soak-builder:
    name: Build and push 'soak-builder' (${{ matrix.platform }})
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a
        with:
          images: ghcr.io/${{ github.repository }}/soak-builder
          flavor: |
            latest=true
          tags: type=sha, format=long
          labels: |
            org.opencontainers.image.description=Base image for use with building soak-vector images
            org.opencontainers.image.title=Soak Builder

      - name: Build and push Docker image (linux/amd64)
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          file: soaks/Dockerfile.builder
          push: ${{ github.ref == 'refs/heads/master' }}
          platforms: ${{ matrix.platform }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
