# Build soak test infra
#
# This workflow builds our soak test infrastructure. The image here is
# built on a push to master branch that update the 'lib/soak' directory.
name: Soak Infra

on:
  pull_request:
    paths:
      - 'lib/soak'
      - '.github/workflows/soak_infra.yml'
  push:
    branches:
      - master
    paths:
      - 'lib/soak'
      - '.github/workflows/soak_infra.yml'

jobs:
  cancel-previous:
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          all_but_latest: true # can cancel workflows scheduled later

  observer:
    name: Build and push 'observer' to Github CR
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@e5622373a38e60fb6d795a4421e56882f2d7a681
        with:
          images: ghcr.io/${{ github.repository }}/soak-observer
          flavor: |
            latest=true
          tags: type=sha, format=long
          labels: |
            org.opencontainers.image.description=Inspects a Prometheus with a configured query, used in Vector soak infra.
            org.opencontainers.image.source=https://github.com/vectordotdev/vector/tree/master/lib/soak
            org.opencontainers.image.title=Soak Observer
            org.opencontainers.image.url=https://github.com/vectordotdev/vector/tree/master/lib/soak

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          file: lib/soak/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  soak-builder:
    name: Build and push 'soak-builder' to Github CR
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@e5622373a38e60fb6d795a4421e56882f2d7a681
        with:
          images: ghcr.io/${{ github.repository }}/soak-builder
          flavor: |
            latest=true
          tags: type=sha, format=long
          labels: |
            org.opencontainers.image.description=Base image for use with building soak-vector images
            org.opencontainers.image.title=Soak Builder

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          file: soaks/Dockerfile.builder
          push: ${{ github.ref == 'refs/heads/master' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
